// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AggregateOptions {
 *     int8_t allow_disk_use;
 *     int32_t batch_size;
 *     int8_t bypass_document_validation;
 *     const struct Bson *collation;
 *     const struct BsonValue *comment;
 *     const char *hint_name;
 *     const struct Bson *hint_keys;
 *     int64_t max_time_ms;
 *     const struct Bson *let_vars;
 * }
 * }
 */
public class AggregateOptions {

    AggregateOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_CHAR.withName("allow_disk_use"),
        MemoryLayout.paddingLayout(3),
        MongoDbFfi.C_INT.withName("batch_size"),
        MongoDbFfi.C_CHAR.withName("bypass_document_validation"),
        MemoryLayout.paddingLayout(7),
        MongoDbFfi.C_POINTER.withName("collation"),
        MongoDbFfi.C_POINTER.withName("comment"),
        MongoDbFfi.C_POINTER.withName("hint_name"),
        MongoDbFfi.C_POINTER.withName("hint_keys"),
        MongoDbFfi.C_LONG_LONG.withName("max_time_ms"),
        MongoDbFfi.C_POINTER.withName("let_vars")
    ).withName("AggregateOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte allow_disk_use$LAYOUT = (OfByte)$LAYOUT.select(groupElement("allow_disk_use"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t allow_disk_use
     * }
     */
    public static final OfByte allow_disk_use$layout() {
        return allow_disk_use$LAYOUT;
    }

    private static final long allow_disk_use$OFFSET = $LAYOUT.byteOffset(groupElement("allow_disk_use"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t allow_disk_use
     * }
     */
    public static final long allow_disk_use$offset() {
        return allow_disk_use$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t allow_disk_use
     * }
     */
    public static byte allow_disk_use(MemorySegment struct) {
        return struct.get(allow_disk_use$LAYOUT, allow_disk_use$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t allow_disk_use
     * }
     */
    public static void allow_disk_use(MemorySegment struct, byte fieldValue) {
        struct.set(allow_disk_use$LAYOUT, allow_disk_use$OFFSET, fieldValue);
    }

    private static final OfInt batch_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("batch_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static final OfInt batch_size$layout() {
        return batch_size$LAYOUT;
    }

    private static final long batch_size$OFFSET = $LAYOUT.byteOffset(groupElement("batch_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static final long batch_size$offset() {
        return batch_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static int batch_size(MemorySegment struct) {
        return struct.get(batch_size$LAYOUT, batch_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static void batch_size(MemorySegment struct, int fieldValue) {
        struct.set(batch_size$LAYOUT, batch_size$OFFSET, fieldValue);
    }

    private static final OfByte bypass_document_validation$LAYOUT = (OfByte)$LAYOUT.select(groupElement("bypass_document_validation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static final OfByte bypass_document_validation$layout() {
        return bypass_document_validation$LAYOUT;
    }

    private static final long bypass_document_validation$OFFSET = $LAYOUT.byteOffset(groupElement("bypass_document_validation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static final long bypass_document_validation$offset() {
        return bypass_document_validation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static byte bypass_document_validation(MemorySegment struct) {
        return struct.get(bypass_document_validation$LAYOUT, bypass_document_validation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static void bypass_document_validation(MemorySegment struct, byte fieldValue) {
        struct.set(bypass_document_validation$LAYOUT, bypass_document_validation$OFFSET, fieldValue);
    }

    private static final AddressLayout collation$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("collation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final AddressLayout collation$layout() {
        return collation$LAYOUT;
    }

    private static final long collation$OFFSET = $LAYOUT.byteOffset(groupElement("collation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final long collation$offset() {
        return collation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static MemorySegment collation(MemorySegment struct) {
        return struct.get(collation$LAYOUT, collation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static void collation(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(collation$LAYOUT, collation$OFFSET, fieldValue);
    }

    private static final AddressLayout comment$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("comment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final AddressLayout comment$layout() {
        return comment$LAYOUT;
    }

    private static final long comment$OFFSET = $LAYOUT.byteOffset(groupElement("comment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final long comment$offset() {
        return comment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static MemorySegment comment(MemorySegment struct) {
        return struct.get(comment$LAYOUT, comment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static void comment(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(comment$LAYOUT, comment$OFFSET, fieldValue);
    }

    private static final AddressLayout hint_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("hint_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *hint_name
     * }
     */
    public static final AddressLayout hint_name$layout() {
        return hint_name$LAYOUT;
    }

    private static final long hint_name$OFFSET = $LAYOUT.byteOffset(groupElement("hint_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *hint_name
     * }
     */
    public static final long hint_name$offset() {
        return hint_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *hint_name
     * }
     */
    public static MemorySegment hint_name(MemorySegment struct) {
        return struct.get(hint_name$LAYOUT, hint_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *hint_name
     * }
     */
    public static void hint_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hint_name$LAYOUT, hint_name$OFFSET, fieldValue);
    }

    private static final AddressLayout hint_keys$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("hint_keys"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *hint_keys
     * }
     */
    public static final AddressLayout hint_keys$layout() {
        return hint_keys$LAYOUT;
    }

    private static final long hint_keys$OFFSET = $LAYOUT.byteOffset(groupElement("hint_keys"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *hint_keys
     * }
     */
    public static final long hint_keys$offset() {
        return hint_keys$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *hint_keys
     * }
     */
    public static MemorySegment hint_keys(MemorySegment struct) {
        return struct.get(hint_keys$LAYOUT, hint_keys$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *hint_keys
     * }
     */
    public static void hint_keys(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hint_keys$LAYOUT, hint_keys$OFFSET, fieldValue);
    }

    private static final OfLong max_time_ms$LAYOUT = (OfLong)$LAYOUT.select(groupElement("max_time_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t max_time_ms
     * }
     */
    public static final OfLong max_time_ms$layout() {
        return max_time_ms$LAYOUT;
    }

    private static final long max_time_ms$OFFSET = $LAYOUT.byteOffset(groupElement("max_time_ms"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t max_time_ms
     * }
     */
    public static final long max_time_ms$offset() {
        return max_time_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t max_time_ms
     * }
     */
    public static long max_time_ms(MemorySegment struct) {
        return struct.get(max_time_ms$LAYOUT, max_time_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t max_time_ms
     * }
     */
    public static void max_time_ms(MemorySegment struct, long fieldValue) {
        struct.set(max_time_ms$LAYOUT, max_time_ms$OFFSET, fieldValue);
    }

    private static final AddressLayout let_vars$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("let_vars"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *let_vars
     * }
     */
    public static final AddressLayout let_vars$layout() {
        return let_vars$LAYOUT;
    }

    private static final long let_vars$OFFSET = $LAYOUT.byteOffset(groupElement("let_vars"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *let_vars
     * }
     */
    public static final long let_vars$offset() {
        return let_vars$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *let_vars
     * }
     */
    public static MemorySegment let_vars(MemorySegment struct) {
        return struct.get(let_vars$LAYOUT, let_vars$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *let_vars
     * }
     */
    public static void let_vars(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(let_vars$LAYOUT, let_vars$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

