// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AuthSettings {
 *     const char *mechanism;
 *     const char *username;
 *     const char *password;
 *     const char *source;
 * }
 * }
 */
public class AuthSettings {

    AuthSettings() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_POINTER.withName("mechanism"),
        MongoDbFfi.C_POINTER.withName("username"),
        MongoDbFfi.C_POINTER.withName("password"),
        MongoDbFfi.C_POINTER.withName("source")
    ).withName("AuthSettings");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout mechanism$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("mechanism"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *mechanism
     * }
     */
    public static final AddressLayout mechanism$layout() {
        return mechanism$LAYOUT;
    }

    private static final long mechanism$OFFSET = $LAYOUT.byteOffset(groupElement("mechanism"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *mechanism
     * }
     */
    public static final long mechanism$offset() {
        return mechanism$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *mechanism
     * }
     */
    public static MemorySegment mechanism(MemorySegment struct) {
        return struct.get(mechanism$LAYOUT, mechanism$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *mechanism
     * }
     */
    public static void mechanism(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(mechanism$LAYOUT, mechanism$OFFSET, fieldValue);
    }

    private static final AddressLayout username$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("username"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *username
     * }
     */
    public static final AddressLayout username$layout() {
        return username$LAYOUT;
    }

    private static final long username$OFFSET = $LAYOUT.byteOffset(groupElement("username"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *username
     * }
     */
    public static final long username$offset() {
        return username$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *username
     * }
     */
    public static MemorySegment username(MemorySegment struct) {
        return struct.get(username$LAYOUT, username$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *username
     * }
     */
    public static void username(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(username$LAYOUT, username$OFFSET, fieldValue);
    }

    private static final AddressLayout password$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("password"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *password
     * }
     */
    public static final AddressLayout password$layout() {
        return password$LAYOUT;
    }

    private static final long password$OFFSET = $LAYOUT.byteOffset(groupElement("password"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *password
     * }
     */
    public static final long password$offset() {
        return password$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *password
     * }
     */
    public static MemorySegment password(MemorySegment struct) {
        return struct.get(password$LAYOUT, password$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *password
     * }
     */
    public static void password(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(password$LAYOUT, password$OFFSET, fieldValue);
    }

    private static final AddressLayout source$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("source"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *source
     * }
     */
    public static final AddressLayout source$layout() {
        return source$LAYOUT;
    }

    private static final long source$OFFSET = $LAYOUT.byteOffset(groupElement("source"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *source
     * }
     */
    public static final long source$offset() {
        return source$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *source
     * }
     */
    public static MemorySegment source(MemorySegment struct) {
        return struct.get(source$LAYOUT, source$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *source
     * }
     */
    public static void source(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(source$LAYOUT, source$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

