// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct BulkWriteResult {
 *     uint64_t inserted_count;
 *     uint64_t matched_count;
 *     uint64_t modified_count;
 *     uint64_t deleted_count;
 *     uint64_t upserted_count;
 *     struct Bson inserted_ids;
 *     struct Bson upserted_ids;
 * }
 * }
 */
public class BulkWriteResult {

    BulkWriteResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_LONG_LONG.withName("inserted_count"),
        MongoDbFfi.C_LONG_LONG.withName("matched_count"),
        MongoDbFfi.C_LONG_LONG.withName("modified_count"),
        MongoDbFfi.C_LONG_LONG.withName("deleted_count"),
        MongoDbFfi.C_LONG_LONG.withName("upserted_count"),
        Bson.layout().withName("inserted_ids"),
        Bson.layout().withName("upserted_ids")
    ).withName("BulkWriteResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong inserted_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("inserted_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t inserted_count
     * }
     */
    public static final OfLong inserted_count$layout() {
        return inserted_count$LAYOUT;
    }

    private static final long inserted_count$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t inserted_count
     * }
     */
    public static final long inserted_count$offset() {
        return inserted_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t inserted_count
     * }
     */
    public static long inserted_count(MemorySegment struct) {
        return struct.get(inserted_count$LAYOUT, inserted_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t inserted_count
     * }
     */
    public static void inserted_count(MemorySegment struct, long fieldValue) {
        struct.set(inserted_count$LAYOUT, inserted_count$OFFSET, fieldValue);
    }

    private static final OfLong matched_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("matched_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t matched_count
     * }
     */
    public static final OfLong matched_count$layout() {
        return matched_count$LAYOUT;
    }

    private static final long matched_count$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t matched_count
     * }
     */
    public static final long matched_count$offset() {
        return matched_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t matched_count
     * }
     */
    public static long matched_count(MemorySegment struct) {
        return struct.get(matched_count$LAYOUT, matched_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t matched_count
     * }
     */
    public static void matched_count(MemorySegment struct, long fieldValue) {
        struct.set(matched_count$LAYOUT, matched_count$OFFSET, fieldValue);
    }

    private static final OfLong modified_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("modified_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t modified_count
     * }
     */
    public static final OfLong modified_count$layout() {
        return modified_count$LAYOUT;
    }

    private static final long modified_count$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t modified_count
     * }
     */
    public static final long modified_count$offset() {
        return modified_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t modified_count
     * }
     */
    public static long modified_count(MemorySegment struct) {
        return struct.get(modified_count$LAYOUT, modified_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t modified_count
     * }
     */
    public static void modified_count(MemorySegment struct, long fieldValue) {
        struct.set(modified_count$LAYOUT, modified_count$OFFSET, fieldValue);
    }

    private static final OfLong deleted_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("deleted_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t deleted_count
     * }
     */
    public static final OfLong deleted_count$layout() {
        return deleted_count$LAYOUT;
    }

    private static final long deleted_count$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t deleted_count
     * }
     */
    public static final long deleted_count$offset() {
        return deleted_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t deleted_count
     * }
     */
    public static long deleted_count(MemorySegment struct) {
        return struct.get(deleted_count$LAYOUT, deleted_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t deleted_count
     * }
     */
    public static void deleted_count(MemorySegment struct, long fieldValue) {
        struct.set(deleted_count$LAYOUT, deleted_count$OFFSET, fieldValue);
    }

    private static final OfLong upserted_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("upserted_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t upserted_count
     * }
     */
    public static final OfLong upserted_count$layout() {
        return upserted_count$LAYOUT;
    }

    private static final long upserted_count$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t upserted_count
     * }
     */
    public static final long upserted_count$offset() {
        return upserted_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t upserted_count
     * }
     */
    public static long upserted_count(MemorySegment struct) {
        return struct.get(upserted_count$LAYOUT, upserted_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t upserted_count
     * }
     */
    public static void upserted_count(MemorySegment struct, long fieldValue) {
        struct.set(upserted_count$LAYOUT, upserted_count$OFFSET, fieldValue);
    }

    private static final GroupLayout inserted_ids$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("inserted_ids"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct Bson inserted_ids
     * }
     */
    public static final GroupLayout inserted_ids$layout() {
        return inserted_ids$LAYOUT;
    }

    private static final long inserted_ids$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct Bson inserted_ids
     * }
     */
    public static final long inserted_ids$offset() {
        return inserted_ids$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct Bson inserted_ids
     * }
     */
    public static MemorySegment inserted_ids(MemorySegment struct) {
        return struct.asSlice(inserted_ids$OFFSET, inserted_ids$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct Bson inserted_ids
     * }
     */
    public static void inserted_ids(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, inserted_ids$OFFSET, inserted_ids$LAYOUT.byteSize());
    }

    private static final GroupLayout upserted_ids$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("upserted_ids"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct Bson upserted_ids
     * }
     */
    public static final GroupLayout upserted_ids$layout() {
        return upserted_ids$LAYOUT;
    }

    private static final long upserted_ids$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct Bson upserted_ids
     * }
     */
    public static final long upserted_ids$offset() {
        return upserted_ids$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct Bson upserted_ids
     * }
     */
    public static MemorySegment upserted_ids(MemorySegment struct) {
        return struct.asSlice(upserted_ids$OFFSET, upserted_ids$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct Bson upserted_ids
     * }
     */
    public static void upserted_ids(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, upserted_ids$OFFSET, upserted_ids$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

