// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct BulkWriteError {
 *     const struct WriteError *write_errors;
 *     uintptr_t write_errors_len;
 *     const struct WriteConcernError *write_concern_error;
 *     const struct BulkWriteResult *partial_result;
 * }
 * }
 */
public class BulkWriteError {

    BulkWriteError() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_POINTER.withName("write_errors"),
        MongoDbFfi.C_LONG.withName("write_errors_len"),
        MongoDbFfi.C_POINTER.withName("write_concern_error"),
        MongoDbFfi.C_POINTER.withName("partial_result")
    ).withName("BulkWriteError");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout write_errors$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("write_errors"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct WriteError *write_errors
     * }
     */
    public static final AddressLayout write_errors$layout() {
        return write_errors$LAYOUT;
    }

    private static final long write_errors$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct WriteError *write_errors
     * }
     */
    public static final long write_errors$offset() {
        return write_errors$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct WriteError *write_errors
     * }
     */
    public static MemorySegment write_errors(MemorySegment struct) {
        return struct.get(write_errors$LAYOUT, write_errors$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct WriteError *write_errors
     * }
     */
    public static void write_errors(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(write_errors$LAYOUT, write_errors$OFFSET, fieldValue);
    }

    private static final OfLong write_errors_len$LAYOUT = (OfLong)$LAYOUT.select(groupElement("write_errors_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uintptr_t write_errors_len
     * }
     */
    public static final OfLong write_errors_len$layout() {
        return write_errors_len$LAYOUT;
    }

    private static final long write_errors_len$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uintptr_t write_errors_len
     * }
     */
    public static final long write_errors_len$offset() {
        return write_errors_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uintptr_t write_errors_len
     * }
     */
    public static long write_errors_len(MemorySegment struct) {
        return struct.get(write_errors_len$LAYOUT, write_errors_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uintptr_t write_errors_len
     * }
     */
    public static void write_errors_len(MemorySegment struct, long fieldValue) {
        struct.set(write_errors_len$LAYOUT, write_errors_len$OFFSET, fieldValue);
    }

    private static final AddressLayout write_concern_error$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("write_concern_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct WriteConcernError *write_concern_error
     * }
     */
    public static final AddressLayout write_concern_error$layout() {
        return write_concern_error$LAYOUT;
    }

    private static final long write_concern_error$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct WriteConcernError *write_concern_error
     * }
     */
    public static final long write_concern_error$offset() {
        return write_concern_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct WriteConcernError *write_concern_error
     * }
     */
    public static MemorySegment write_concern_error(MemorySegment struct) {
        return struct.get(write_concern_error$LAYOUT, write_concern_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct WriteConcernError *write_concern_error
     * }
     */
    public static void write_concern_error(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(write_concern_error$LAYOUT, write_concern_error$OFFSET, fieldValue);
    }

    private static final AddressLayout partial_result$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("partial_result"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BulkWriteResult *partial_result
     * }
     */
    public static final AddressLayout partial_result$layout() {
        return partial_result$LAYOUT;
    }

    private static final long partial_result$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BulkWriteResult *partial_result
     * }
     */
    public static final long partial_result$offset() {
        return partial_result$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BulkWriteResult *partial_result
     * }
     */
    public static MemorySegment partial_result(MemorySegment struct) {
        return struct.get(partial_result$LAYOUT, partial_result$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BulkWriteResult *partial_result
     * }
     */
    public static void partial_result(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(partial_result$LAYOUT, partial_result$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

