// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ChangeStreamGetMoreResult {
 *     bool exhausted;
 *     struct BsonBatch batch;
 *     struct Bson resume_token;
 * }
 * }
 */
public class ChangeStreamGetMoreResult {

    ChangeStreamGetMoreResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_BOOL.withName("exhausted"),
        MemoryLayout.paddingLayout(7),
        BsonBatch.layout().withName("batch"),
        Bson.layout().withName("resume_token")
    ).withName("ChangeStreamGetMoreResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfBoolean exhausted$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("exhausted"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool exhausted
     * }
     */
    public static final OfBoolean exhausted$layout() {
        return exhausted$LAYOUT;
    }

    private static final long exhausted$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool exhausted
     * }
     */
    public static final long exhausted$offset() {
        return exhausted$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool exhausted
     * }
     */
    public static boolean exhausted(MemorySegment struct) {
        return struct.get(exhausted$LAYOUT, exhausted$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool exhausted
     * }
     */
    public static void exhausted(MemorySegment struct, boolean fieldValue) {
        struct.set(exhausted$LAYOUT, exhausted$OFFSET, fieldValue);
    }

    private static final GroupLayout batch$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("batch"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct BsonBatch batch
     * }
     */
    public static final GroupLayout batch$layout() {
        return batch$LAYOUT;
    }

    private static final long batch$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct BsonBatch batch
     * }
     */
    public static final long batch$offset() {
        return batch$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct BsonBatch batch
     * }
     */
    public static MemorySegment batch(MemorySegment struct) {
        return struct.asSlice(batch$OFFSET, batch$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct BsonBatch batch
     * }
     */
    public static void batch(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, batch$OFFSET, batch$LAYOUT.byteSize());
    }

    private static final GroupLayout resume_token$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("resume_token"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct Bson resume_token
     * }
     */
    public static final GroupLayout resume_token$layout() {
        return resume_token$LAYOUT;
    }

    private static final long resume_token$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct Bson resume_token
     * }
     */
    public static final long resume_token$offset() {
        return resume_token$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct Bson resume_token
     * }
     */
    public static MemorySegment resume_token(MemorySegment struct) {
        return struct.asSlice(resume_token$OFFSET, resume_token$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct Bson resume_token
     * }
     */
    public static void resume_token(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, resume_token$OFFSET, resume_token$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

