// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*ChangeStreamResultCallback)(void *, const struct ChangeStreamResult {
 *     struct ChangeStream *cursor;
 *     struct BsonBatch first_batch;
 *     struct Bson resume_token;
 *     const char *server_address;
 *     uint16_t server_port;
 * } *, const struct Error {
 *     ErrorType error_type;
 *     union ErrorUnion error;
 * } *)
 * }
 */
public final class ChangeStreamResultCallback {

    private ChangeStreamResultCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment userdata, MemorySegment result, MemorySegment error);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        MongoDbFfi.C_POINTER,
        MongoDbFfi.C_POINTER,
        MongoDbFfi.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = MongoDbFfi.upcallHandle(ChangeStreamResultCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(ChangeStreamResultCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment userdata, MemorySegment result, MemorySegment error) {
        try {
             DOWN$MH.invokeExact(funcPtr, userdata, result, error);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

