// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ChangeStreamOptions {
 *     int8_t full_document;
 *     int8_t full_document_before_change;
 *     const struct Bson *resume_after;
 *     const struct Bson *start_after;
 *     const struct Bson *start_at_operation_time;
 *     int32_t batch_size;
 *     const struct Bson *collation;
 *     const struct BsonValue *comment;
 * }
 * }
 */
public class ChangeStreamOptions {

    ChangeStreamOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_CHAR.withName("full_document"),
        MongoDbFfi.C_CHAR.withName("full_document_before_change"),
        MemoryLayout.paddingLayout(6),
        MongoDbFfi.C_POINTER.withName("resume_after"),
        MongoDbFfi.C_POINTER.withName("start_after"),
        MongoDbFfi.C_POINTER.withName("start_at_operation_time"),
        MongoDbFfi.C_INT.withName("batch_size"),
        MemoryLayout.paddingLayout(4),
        MongoDbFfi.C_POINTER.withName("collation"),
        MongoDbFfi.C_POINTER.withName("comment")
    ).withName("ChangeStreamOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte full_document$LAYOUT = (OfByte)$LAYOUT.select(groupElement("full_document"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t full_document
     * }
     */
    public static final OfByte full_document$layout() {
        return full_document$LAYOUT;
    }

    private static final long full_document$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t full_document
     * }
     */
    public static final long full_document$offset() {
        return full_document$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t full_document
     * }
     */
    public static byte full_document(MemorySegment struct) {
        return struct.get(full_document$LAYOUT, full_document$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t full_document
     * }
     */
    public static void full_document(MemorySegment struct, byte fieldValue) {
        struct.set(full_document$LAYOUT, full_document$OFFSET, fieldValue);
    }

    private static final OfByte full_document_before_change$LAYOUT = (OfByte)$LAYOUT.select(groupElement("full_document_before_change"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t full_document_before_change
     * }
     */
    public static final OfByte full_document_before_change$layout() {
        return full_document_before_change$LAYOUT;
    }

    private static final long full_document_before_change$OFFSET = 1;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t full_document_before_change
     * }
     */
    public static final long full_document_before_change$offset() {
        return full_document_before_change$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t full_document_before_change
     * }
     */
    public static byte full_document_before_change(MemorySegment struct) {
        return struct.get(full_document_before_change$LAYOUT, full_document_before_change$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t full_document_before_change
     * }
     */
    public static void full_document_before_change(MemorySegment struct, byte fieldValue) {
        struct.set(full_document_before_change$LAYOUT, full_document_before_change$OFFSET, fieldValue);
    }

    private static final AddressLayout resume_after$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("resume_after"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *resume_after
     * }
     */
    public static final AddressLayout resume_after$layout() {
        return resume_after$LAYOUT;
    }

    private static final long resume_after$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *resume_after
     * }
     */
    public static final long resume_after$offset() {
        return resume_after$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *resume_after
     * }
     */
    public static MemorySegment resume_after(MemorySegment struct) {
        return struct.get(resume_after$LAYOUT, resume_after$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *resume_after
     * }
     */
    public static void resume_after(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(resume_after$LAYOUT, resume_after$OFFSET, fieldValue);
    }

    private static final AddressLayout start_after$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("start_after"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *start_after
     * }
     */
    public static final AddressLayout start_after$layout() {
        return start_after$LAYOUT;
    }

    private static final long start_after$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *start_after
     * }
     */
    public static final long start_after$offset() {
        return start_after$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *start_after
     * }
     */
    public static MemorySegment start_after(MemorySegment struct) {
        return struct.get(start_after$LAYOUT, start_after$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *start_after
     * }
     */
    public static void start_after(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(start_after$LAYOUT, start_after$OFFSET, fieldValue);
    }

    private static final AddressLayout start_at_operation_time$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("start_at_operation_time"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *start_at_operation_time
     * }
     */
    public static final AddressLayout start_at_operation_time$layout() {
        return start_at_operation_time$LAYOUT;
    }

    private static final long start_at_operation_time$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *start_at_operation_time
     * }
     */
    public static final long start_at_operation_time$offset() {
        return start_at_operation_time$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *start_at_operation_time
     * }
     */
    public static MemorySegment start_at_operation_time(MemorySegment struct) {
        return struct.get(start_at_operation_time$LAYOUT, start_at_operation_time$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *start_at_operation_time
     * }
     */
    public static void start_at_operation_time(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(start_at_operation_time$LAYOUT, start_at_operation_time$OFFSET, fieldValue);
    }

    private static final OfInt batch_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("batch_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static final OfInt batch_size$layout() {
        return batch_size$LAYOUT;
    }

    private static final long batch_size$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static final long batch_size$offset() {
        return batch_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static int batch_size(MemorySegment struct) {
        return struct.get(batch_size$LAYOUT, batch_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static void batch_size(MemorySegment struct, int fieldValue) {
        struct.set(batch_size$LAYOUT, batch_size$OFFSET, fieldValue);
    }

    private static final AddressLayout collation$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("collation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final AddressLayout collation$layout() {
        return collation$LAYOUT;
    }

    private static final long collation$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final long collation$offset() {
        return collation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static MemorySegment collation(MemorySegment struct) {
        return struct.get(collation$LAYOUT, collation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static void collation(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(collation$LAYOUT, collation$OFFSET, fieldValue);
    }

    private static final AddressLayout comment$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("comment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final AddressLayout comment$layout() {
        return comment$LAYOUT;
    }

    private static final long comment$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final long comment$offset() {
        return comment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static MemorySegment comment(MemorySegment struct) {
        return struct.get(comment$LAYOUT, comment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static void comment(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(comment$LAYOUT, comment$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

