// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct CreateIndexResult {
 *     const char *index_name;
 * }
 * }
 */
public class CreateIndexResult {

    CreateIndexResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_POINTER.withName("index_name")
    ).withName("CreateIndexResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout index_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("index_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *index_name
     * }
     */
    public static final AddressLayout index_name$layout() {
        return index_name$LAYOUT;
    }

    private static final long index_name$OFFSET = $LAYOUT.byteOffset(groupElement("index_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *index_name
     * }
     */
    public static final long index_name$offset() {
        return index_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *index_name
     * }
     */
    public static MemorySegment index_name(MemorySegment struct) {
        return struct.get(index_name$LAYOUT, index_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *index_name
     * }
     */
    public static void index_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(index_name$LAYOUT, index_name$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

