// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct CreateCollectionOptions {
 *     int8_t capped;
 *     int64_t size;
 *     int64_t max;
 *     const struct Bson *storage_engine;
 *     const struct Bson *validator;
 *     const char *validation_level;
 *     const char *validation_action;
 *     const struct Bson *collation;
 *     int64_t expire_after_seconds;
 *     const struct Bson *timeseries;
 * }
 * }
 */
public class CreateCollectionOptions {

    CreateCollectionOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_CHAR.withName("capped"),
        MemoryLayout.paddingLayout(7),
        MongoDbFfi.C_LONG_LONG.withName("size"),
        MongoDbFfi.C_LONG_LONG.withName("max"),
        MongoDbFfi.C_POINTER.withName("storage_engine"),
        MongoDbFfi.C_POINTER.withName("validator"),
        MongoDbFfi.C_POINTER.withName("validation_level"),
        MongoDbFfi.C_POINTER.withName("validation_action"),
        MongoDbFfi.C_POINTER.withName("collation"),
        MongoDbFfi.C_LONG_LONG.withName("expire_after_seconds"),
        MongoDbFfi.C_POINTER.withName("timeseries")
    ).withName("CreateCollectionOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte capped$LAYOUT = (OfByte)$LAYOUT.select(groupElement("capped"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t capped
     * }
     */
    public static final OfByte capped$layout() {
        return capped$LAYOUT;
    }

    private static final long capped$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t capped
     * }
     */
    public static final long capped$offset() {
        return capped$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t capped
     * }
     */
    public static byte capped(MemorySegment struct) {
        return struct.get(capped$LAYOUT, capped$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t capped
     * }
     */
    public static void capped(MemorySegment struct, byte fieldValue) {
        struct.set(capped$LAYOUT, capped$OFFSET, fieldValue);
    }

    private static final OfLong size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t size
     * }
     */
    public static final OfLong size$layout() {
        return size$LAYOUT;
    }

    private static final long size$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t size
     * }
     */
    public static final long size$offset() {
        return size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t size
     * }
     */
    public static long size(MemorySegment struct) {
        return struct.get(size$LAYOUT, size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t size
     * }
     */
    public static void size(MemorySegment struct, long fieldValue) {
        struct.set(size$LAYOUT, size$OFFSET, fieldValue);
    }

    private static final OfLong max$LAYOUT = (OfLong)$LAYOUT.select(groupElement("max"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t max
     * }
     */
    public static final OfLong max$layout() {
        return max$LAYOUT;
    }

    private static final long max$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t max
     * }
     */
    public static final long max$offset() {
        return max$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t max
     * }
     */
    public static long max(MemorySegment struct) {
        return struct.get(max$LAYOUT, max$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t max
     * }
     */
    public static void max(MemorySegment struct, long fieldValue) {
        struct.set(max$LAYOUT, max$OFFSET, fieldValue);
    }

    private static final AddressLayout storage_engine$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("storage_engine"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *storage_engine
     * }
     */
    public static final AddressLayout storage_engine$layout() {
        return storage_engine$LAYOUT;
    }

    private static final long storage_engine$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *storage_engine
     * }
     */
    public static final long storage_engine$offset() {
        return storage_engine$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *storage_engine
     * }
     */
    public static MemorySegment storage_engine(MemorySegment struct) {
        return struct.get(storage_engine$LAYOUT, storage_engine$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *storage_engine
     * }
     */
    public static void storage_engine(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(storage_engine$LAYOUT, storage_engine$OFFSET, fieldValue);
    }

    private static final AddressLayout validator$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("validator"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *validator
     * }
     */
    public static final AddressLayout validator$layout() {
        return validator$LAYOUT;
    }

    private static final long validator$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *validator
     * }
     */
    public static final long validator$offset() {
        return validator$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *validator
     * }
     */
    public static MemorySegment validator(MemorySegment struct) {
        return struct.get(validator$LAYOUT, validator$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *validator
     * }
     */
    public static void validator(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(validator$LAYOUT, validator$OFFSET, fieldValue);
    }

    private static final AddressLayout validation_level$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("validation_level"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *validation_level
     * }
     */
    public static final AddressLayout validation_level$layout() {
        return validation_level$LAYOUT;
    }

    private static final long validation_level$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *validation_level
     * }
     */
    public static final long validation_level$offset() {
        return validation_level$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *validation_level
     * }
     */
    public static MemorySegment validation_level(MemorySegment struct) {
        return struct.get(validation_level$LAYOUT, validation_level$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *validation_level
     * }
     */
    public static void validation_level(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(validation_level$LAYOUT, validation_level$OFFSET, fieldValue);
    }

    private static final AddressLayout validation_action$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("validation_action"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *validation_action
     * }
     */
    public static final AddressLayout validation_action$layout() {
        return validation_action$LAYOUT;
    }

    private static final long validation_action$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *validation_action
     * }
     */
    public static final long validation_action$offset() {
        return validation_action$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *validation_action
     * }
     */
    public static MemorySegment validation_action(MemorySegment struct) {
        return struct.get(validation_action$LAYOUT, validation_action$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *validation_action
     * }
     */
    public static void validation_action(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(validation_action$LAYOUT, validation_action$OFFSET, fieldValue);
    }

    private static final AddressLayout collation$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("collation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final AddressLayout collation$layout() {
        return collation$LAYOUT;
    }

    private static final long collation$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final long collation$offset() {
        return collation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static MemorySegment collation(MemorySegment struct) {
        return struct.get(collation$LAYOUT, collation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static void collation(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(collation$LAYOUT, collation$OFFSET, fieldValue);
    }

    private static final OfLong expire_after_seconds$LAYOUT = (OfLong)$LAYOUT.select(groupElement("expire_after_seconds"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t expire_after_seconds
     * }
     */
    public static final OfLong expire_after_seconds$layout() {
        return expire_after_seconds$LAYOUT;
    }

    private static final long expire_after_seconds$OFFSET = 64;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t expire_after_seconds
     * }
     */
    public static final long expire_after_seconds$offset() {
        return expire_after_seconds$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t expire_after_seconds
     * }
     */
    public static long expire_after_seconds(MemorySegment struct) {
        return struct.get(expire_after_seconds$LAYOUT, expire_after_seconds$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t expire_after_seconds
     * }
     */
    public static void expire_after_seconds(MemorySegment struct, long fieldValue) {
        struct.set(expire_after_seconds$LAYOUT, expire_after_seconds$OFFSET, fieldValue);
    }

    private static final AddressLayout timeseries$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("timeseries"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *timeseries
     * }
     */
    public static final AddressLayout timeseries$layout() {
        return timeseries$LAYOUT;
    }

    private static final long timeseries$OFFSET = 72;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *timeseries
     * }
     */
    public static final long timeseries$offset() {
        return timeseries$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *timeseries
     * }
     */
    public static MemorySegment timeseries(MemorySegment struct) {
        return struct.get(timeseries$LAYOUT, timeseries$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *timeseries
     * }
     */
    public static void timeseries(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(timeseries$LAYOUT, timeseries$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

