// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct CursorResult {
 *     struct Cursor *cursor;
 *     bool exhausted;
 *     struct BsonBatch first_batch;
 *     const char *server_address;
 *     uint16_t server_port;
 * }
 * }
 */
public class CursorResult {

    CursorResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_POINTER.withName("cursor"),
        MongoDbFfi.C_BOOL.withName("exhausted"),
        MemoryLayout.paddingLayout(7),
        BsonBatch.layout().withName("first_batch"),
        MongoDbFfi.C_POINTER.withName("server_address"),
        MongoDbFfi.C_SHORT.withName("server_port"),
        MemoryLayout.paddingLayout(6)
    ).withName("CursorResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout cursor$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cursor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct Cursor *cursor
     * }
     */
    public static final AddressLayout cursor$layout() {
        return cursor$LAYOUT;
    }

    private static final long cursor$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct Cursor *cursor
     * }
     */
    public static final long cursor$offset() {
        return cursor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct Cursor *cursor
     * }
     */
    public static MemorySegment cursor(MemorySegment struct) {
        return struct.get(cursor$LAYOUT, cursor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct Cursor *cursor
     * }
     */
    public static void cursor(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cursor$LAYOUT, cursor$OFFSET, fieldValue);
    }

    private static final OfBoolean exhausted$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("exhausted"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool exhausted
     * }
     */
    public static final OfBoolean exhausted$layout() {
        return exhausted$LAYOUT;
    }

    private static final long exhausted$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool exhausted
     * }
     */
    public static final long exhausted$offset() {
        return exhausted$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool exhausted
     * }
     */
    public static boolean exhausted(MemorySegment struct) {
        return struct.get(exhausted$LAYOUT, exhausted$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool exhausted
     * }
     */
    public static void exhausted(MemorySegment struct, boolean fieldValue) {
        struct.set(exhausted$LAYOUT, exhausted$OFFSET, fieldValue);
    }

    private static final GroupLayout first_batch$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("first_batch"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct BsonBatch first_batch
     * }
     */
    public static final GroupLayout first_batch$layout() {
        return first_batch$LAYOUT;
    }

    private static final long first_batch$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct BsonBatch first_batch
     * }
     */
    public static final long first_batch$offset() {
        return first_batch$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct BsonBatch first_batch
     * }
     */
    public static MemorySegment first_batch(MemorySegment struct) {
        return struct.asSlice(first_batch$OFFSET, first_batch$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct BsonBatch first_batch
     * }
     */
    public static void first_batch(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, first_batch$OFFSET, first_batch$LAYOUT.byteSize());
    }

    private static final AddressLayout server_address$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("server_address"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *server_address
     * }
     */
    public static final AddressLayout server_address$layout() {
        return server_address$LAYOUT;
    }

    private static final long server_address$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *server_address
     * }
     */
    public static final long server_address$offset() {
        return server_address$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *server_address
     * }
     */
    public static MemorySegment server_address(MemorySegment struct) {
        return struct.get(server_address$LAYOUT, server_address$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *server_address
     * }
     */
    public static void server_address(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(server_address$LAYOUT, server_address$OFFSET, fieldValue);
    }

    private static final OfShort server_port$LAYOUT = (OfShort)$LAYOUT.select(groupElement("server_port"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t server_port
     * }
     */
    public static final OfShort server_port$layout() {
        return server_port$LAYOUT;
    }

    private static final long server_port$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t server_port
     * }
     */
    public static final long server_port$offset() {
        return server_port$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t server_port
     * }
     */
    public static short server_port(MemorySegment struct) {
        return struct.get(server_port$LAYOUT, server_port$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t server_port
     * }
     */
    public static void server_port(MemorySegment struct, short fieldValue) {
        struct.set(server_port$LAYOUT, server_port$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

