// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct DeleteResult {
 *     uint64_t deleted_count;
 * }
 * }
 */
public class DeleteResult {

    DeleteResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_LONG_LONG.withName("deleted_count")
    ).withName("DeleteResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong deleted_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("deleted_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t deleted_count
     * }
     */
    public static final OfLong deleted_count$layout() {
        return deleted_count$LAYOUT;
    }

    private static final long deleted_count$OFFSET = $LAYOUT.byteOffset(groupElement("deleted_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t deleted_count
     * }
     */
    public static final long deleted_count$offset() {
        return deleted_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t deleted_count
     * }
     */
    public static long deleted_count(MemorySegment struct) {
        return struct.get(deleted_count$LAYOUT, deleted_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t deleted_count
     * }
     */
    public static void deleted_count(MemorySegment struct, long fieldValue) {
        struct.set(deleted_count$LAYOUT, deleted_count$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

