// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * union ErrorUnion {
 *     const struct ServerError *server;
 *     const struct InsertManyError *insert_many;
 *     const struct BulkWriteError *bulk_write;
 *     const struct IoError *io;
 *     const struct ServerSelectionError *server_selection;
 *     const struct TimeoutError *timeout;
 *     const struct AuthError *auth;
 *     const struct InvalidArgumentError *invalid_argument;
 *     const struct TransactionError *transaction;
 *     const struct IncompatibleServerError *incompatible_server;
 *     const struct InvalidResponseError *invalid_response;
 *     const struct ChangeStreamError *change_stream;
 *     const struct ShutdownError *shutdown;
 * }
 * }
 */
public class ErrorUnion {

    ErrorUnion() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
        MongoDbFfi.C_POINTER.withName("server"),
        MongoDbFfi.C_POINTER.withName("insert_many"),
        MongoDbFfi.C_POINTER.withName("bulk_write"),
        MongoDbFfi.C_POINTER.withName("io"),
        MongoDbFfi.C_POINTER.withName("server_selection"),
        MongoDbFfi.C_POINTER.withName("timeout"),
        MongoDbFfi.C_POINTER.withName("auth"),
        MongoDbFfi.C_POINTER.withName("invalid_argument"),
        MongoDbFfi.C_POINTER.withName("transaction"),
        MongoDbFfi.C_POINTER.withName("incompatible_server"),
        MongoDbFfi.C_POINTER.withName("invalid_response"),
        MongoDbFfi.C_POINTER.withName("change_stream"),
        MongoDbFfi.C_POINTER.withName("shutdown")
    ).withName("ErrorUnion");

    /**
     * The layout of this union
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout server$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("server"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct ServerError *server
     * }
     */
    public static final AddressLayout server$layout() {
        return server$LAYOUT;
    }

    private static final long server$OFFSET = $LAYOUT.byteOffset(groupElement("server"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct ServerError *server
     * }
     */
    public static final long server$offset() {
        return server$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct ServerError *server
     * }
     */
    public static MemorySegment server(MemorySegment union) {
        return union.get(server$LAYOUT, server$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct ServerError *server
     * }
     */
    public static void server(MemorySegment union, MemorySegment fieldValue) {
        union.set(server$LAYOUT, server$OFFSET, fieldValue);
    }

    private static final AddressLayout insert_many$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("insert_many"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct InsertManyError *insert_many
     * }
     */
    public static final AddressLayout insert_many$layout() {
        return insert_many$LAYOUT;
    }

    private static final long insert_many$OFFSET = $LAYOUT.byteOffset(groupElement("insert_many"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct InsertManyError *insert_many
     * }
     */
    public static final long insert_many$offset() {
        return insert_many$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct InsertManyError *insert_many
     * }
     */
    public static MemorySegment insert_many(MemorySegment union) {
        return union.get(insert_many$LAYOUT, insert_many$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct InsertManyError *insert_many
     * }
     */
    public static void insert_many(MemorySegment union, MemorySegment fieldValue) {
        union.set(insert_many$LAYOUT, insert_many$OFFSET, fieldValue);
    }

    private static final AddressLayout bulk_write$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("bulk_write"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BulkWriteError *bulk_write
     * }
     */
    public static final AddressLayout bulk_write$layout() {
        return bulk_write$LAYOUT;
    }

    private static final long bulk_write$OFFSET = $LAYOUT.byteOffset(groupElement("bulk_write"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BulkWriteError *bulk_write
     * }
     */
    public static final long bulk_write$offset() {
        return bulk_write$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BulkWriteError *bulk_write
     * }
     */
    public static MemorySegment bulk_write(MemorySegment union) {
        return union.get(bulk_write$LAYOUT, bulk_write$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BulkWriteError *bulk_write
     * }
     */
    public static void bulk_write(MemorySegment union, MemorySegment fieldValue) {
        union.set(bulk_write$LAYOUT, bulk_write$OFFSET, fieldValue);
    }

    private static final AddressLayout io$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("io"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct IoError *io
     * }
     */
    public static final AddressLayout io$layout() {
        return io$LAYOUT;
    }

    private static final long io$OFFSET = $LAYOUT.byteOffset(groupElement("io"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct IoError *io
     * }
     */
    public static final long io$offset() {
        return io$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct IoError *io
     * }
     */
    public static MemorySegment io(MemorySegment union) {
        return union.get(io$LAYOUT, io$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct IoError *io
     * }
     */
    public static void io(MemorySegment union, MemorySegment fieldValue) {
        union.set(io$LAYOUT, io$OFFSET, fieldValue);
    }

    private static final AddressLayout server_selection$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("server_selection"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct ServerSelectionError *server_selection
     * }
     */
    public static final AddressLayout server_selection$layout() {
        return server_selection$LAYOUT;
    }

    private static final long server_selection$OFFSET = $LAYOUT.byteOffset(groupElement("server_selection"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct ServerSelectionError *server_selection
     * }
     */
    public static final long server_selection$offset() {
        return server_selection$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct ServerSelectionError *server_selection
     * }
     */
    public static MemorySegment server_selection(MemorySegment union) {
        return union.get(server_selection$LAYOUT, server_selection$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct ServerSelectionError *server_selection
     * }
     */
    public static void server_selection(MemorySegment union, MemorySegment fieldValue) {
        union.set(server_selection$LAYOUT, server_selection$OFFSET, fieldValue);
    }

    private static final AddressLayout timeout$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("timeout"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TimeoutError *timeout
     * }
     */
    public static final AddressLayout timeout$layout() {
        return timeout$LAYOUT;
    }

    private static final long timeout$OFFSET = $LAYOUT.byteOffset(groupElement("timeout"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TimeoutError *timeout
     * }
     */
    public static final long timeout$offset() {
        return timeout$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TimeoutError *timeout
     * }
     */
    public static MemorySegment timeout(MemorySegment union) {
        return union.get(timeout$LAYOUT, timeout$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TimeoutError *timeout
     * }
     */
    public static void timeout(MemorySegment union, MemorySegment fieldValue) {
        union.set(timeout$LAYOUT, timeout$OFFSET, fieldValue);
    }

    private static final AddressLayout auth$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("auth"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct AuthError *auth
     * }
     */
    public static final AddressLayout auth$layout() {
        return auth$LAYOUT;
    }

    private static final long auth$OFFSET = $LAYOUT.byteOffset(groupElement("auth"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct AuthError *auth
     * }
     */
    public static final long auth$offset() {
        return auth$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct AuthError *auth
     * }
     */
    public static MemorySegment auth(MemorySegment union) {
        return union.get(auth$LAYOUT, auth$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct AuthError *auth
     * }
     */
    public static void auth(MemorySegment union, MemorySegment fieldValue) {
        union.set(auth$LAYOUT, auth$OFFSET, fieldValue);
    }

    private static final AddressLayout invalid_argument$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("invalid_argument"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct InvalidArgumentError *invalid_argument
     * }
     */
    public static final AddressLayout invalid_argument$layout() {
        return invalid_argument$LAYOUT;
    }

    private static final long invalid_argument$OFFSET = $LAYOUT.byteOffset(groupElement("invalid_argument"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct InvalidArgumentError *invalid_argument
     * }
     */
    public static final long invalid_argument$offset() {
        return invalid_argument$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct InvalidArgumentError *invalid_argument
     * }
     */
    public static MemorySegment invalid_argument(MemorySegment union) {
        return union.get(invalid_argument$LAYOUT, invalid_argument$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct InvalidArgumentError *invalid_argument
     * }
     */
    public static void invalid_argument(MemorySegment union, MemorySegment fieldValue) {
        union.set(invalid_argument$LAYOUT, invalid_argument$OFFSET, fieldValue);
    }

    private static final AddressLayout transaction$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("transaction"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TransactionError *transaction
     * }
     */
    public static final AddressLayout transaction$layout() {
        return transaction$LAYOUT;
    }

    private static final long transaction$OFFSET = $LAYOUT.byteOffset(groupElement("transaction"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TransactionError *transaction
     * }
     */
    public static final long transaction$offset() {
        return transaction$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TransactionError *transaction
     * }
     */
    public static MemorySegment transaction(MemorySegment union) {
        return union.get(transaction$LAYOUT, transaction$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TransactionError *transaction
     * }
     */
    public static void transaction(MemorySegment union, MemorySegment fieldValue) {
        union.set(transaction$LAYOUT, transaction$OFFSET, fieldValue);
    }

    private static final AddressLayout incompatible_server$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("incompatible_server"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct IncompatibleServerError *incompatible_server
     * }
     */
    public static final AddressLayout incompatible_server$layout() {
        return incompatible_server$LAYOUT;
    }

    private static final long incompatible_server$OFFSET = $LAYOUT.byteOffset(groupElement("incompatible_server"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct IncompatibleServerError *incompatible_server
     * }
     */
    public static final long incompatible_server$offset() {
        return incompatible_server$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct IncompatibleServerError *incompatible_server
     * }
     */
    public static MemorySegment incompatible_server(MemorySegment union) {
        return union.get(incompatible_server$LAYOUT, incompatible_server$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct IncompatibleServerError *incompatible_server
     * }
     */
    public static void incompatible_server(MemorySegment union, MemorySegment fieldValue) {
        union.set(incompatible_server$LAYOUT, incompatible_server$OFFSET, fieldValue);
    }

    private static final AddressLayout invalid_response$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("invalid_response"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct InvalidResponseError *invalid_response
     * }
     */
    public static final AddressLayout invalid_response$layout() {
        return invalid_response$LAYOUT;
    }

    private static final long invalid_response$OFFSET = $LAYOUT.byteOffset(groupElement("invalid_response"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct InvalidResponseError *invalid_response
     * }
     */
    public static final long invalid_response$offset() {
        return invalid_response$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct InvalidResponseError *invalid_response
     * }
     */
    public static MemorySegment invalid_response(MemorySegment union) {
        return union.get(invalid_response$LAYOUT, invalid_response$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct InvalidResponseError *invalid_response
     * }
     */
    public static void invalid_response(MemorySegment union, MemorySegment fieldValue) {
        union.set(invalid_response$LAYOUT, invalid_response$OFFSET, fieldValue);
    }

    private static final AddressLayout change_stream$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("change_stream"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct ChangeStreamError *change_stream
     * }
     */
    public static final AddressLayout change_stream$layout() {
        return change_stream$LAYOUT;
    }

    private static final long change_stream$OFFSET = $LAYOUT.byteOffset(groupElement("change_stream"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct ChangeStreamError *change_stream
     * }
     */
    public static final long change_stream$offset() {
        return change_stream$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct ChangeStreamError *change_stream
     * }
     */
    public static MemorySegment change_stream(MemorySegment union) {
        return union.get(change_stream$LAYOUT, change_stream$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct ChangeStreamError *change_stream
     * }
     */
    public static void change_stream(MemorySegment union, MemorySegment fieldValue) {
        union.set(change_stream$LAYOUT, change_stream$OFFSET, fieldValue);
    }

    private static final AddressLayout shutdown$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("shutdown"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct ShutdownError *shutdown
     * }
     */
    public static final AddressLayout shutdown$layout() {
        return shutdown$LAYOUT;
    }

    private static final long shutdown$OFFSET = $LAYOUT.byteOffset(groupElement("shutdown"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct ShutdownError *shutdown
     * }
     */
    public static final long shutdown$offset() {
        return shutdown$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct ShutdownError *shutdown
     * }
     */
    public static MemorySegment shutdown(MemorySegment union) {
        return union.get(shutdown$LAYOUT, shutdown$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct ShutdownError *shutdown
     * }
     */
    public static void shutdown(MemorySegment union, MemorySegment fieldValue) {
        union.set(shutdown$LAYOUT, shutdown$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this union
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

