// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct Error {
 *     ErrorType error_type;
 *     union ErrorUnion error;
 * }
 * }
 */
public class Error {

    Error() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_CHAR.withName("error_type"),
        MemoryLayout.paddingLayout(7),
        ErrorUnion.layout().withName("error")
    ).withName("Error");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte error_type$LAYOUT = (OfByte)$LAYOUT.select(groupElement("error_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ErrorType error_type
     * }
     */
    public static final OfByte error_type$layout() {
        return error_type$LAYOUT;
    }

    private static final long error_type$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ErrorType error_type
     * }
     */
    public static final long error_type$offset() {
        return error_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ErrorType error_type
     * }
     */
    public static byte error_type(MemorySegment struct) {
        return struct.get(error_type$LAYOUT, error_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ErrorType error_type
     * }
     */
    public static void error_type(MemorySegment struct, byte fieldValue) {
        struct.set(error_type$LAYOUT, error_type$OFFSET, fieldValue);
    }

    private static final GroupLayout error$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union ErrorUnion error
     * }
     */
    public static final GroupLayout error$layout() {
        return error$LAYOUT;
    }

    private static final long error$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union ErrorUnion error
     * }
     */
    public static final long error$offset() {
        return error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union ErrorUnion error
     * }
     */
    public static MemorySegment error(MemorySegment struct) {
        return struct.asSlice(error$OFFSET, error$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union ErrorUnion error
     * }
     */
    public static void error(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, error$OFFSET, error$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

