// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct FfiCommandFailedEvent {
 *     const char *command_name;
 *     int32_t request_id;
 *     uint32_t connection_id;
 *     int64_t connection_server_id;
 *     const char *connection_address;
 *     uint8_t service_id[12];
 *     bool has_service_id;
 *     uint64_t duration_nanos;
 *     const struct Error *failure;
 * }
 * }
 */
public class FfiCommandFailedEvent {

    FfiCommandFailedEvent() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_POINTER.withName("command_name"),
        MongoDbFfi.C_INT.withName("request_id"),
        MongoDbFfi.C_INT.withName("connection_id"),
        MongoDbFfi.C_LONG_LONG.withName("connection_server_id"),
        MongoDbFfi.C_POINTER.withName("connection_address"),
        MemoryLayout.sequenceLayout(12, MongoDbFfi.C_CHAR).withName("service_id"),
        MongoDbFfi.C_BOOL.withName("has_service_id"),
        MemoryLayout.paddingLayout(3),
        MongoDbFfi.C_LONG_LONG.withName("duration_nanos"),
        MongoDbFfi.C_POINTER.withName("failure")
    ).withName("FfiCommandFailedEvent");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout command_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("command_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *command_name
     * }
     */
    public static final AddressLayout command_name$layout() {
        return command_name$LAYOUT;
    }

    private static final long command_name$OFFSET = $LAYOUT.byteOffset(groupElement("command_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *command_name
     * }
     */
    public static final long command_name$offset() {
        return command_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *command_name
     * }
     */
    public static MemorySegment command_name(MemorySegment struct) {
        return struct.get(command_name$LAYOUT, command_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *command_name
     * }
     */
    public static void command_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(command_name$LAYOUT, command_name$OFFSET, fieldValue);
    }

    private static final OfInt request_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("request_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t request_id
     * }
     */
    public static final OfInt request_id$layout() {
        return request_id$LAYOUT;
    }

    private static final long request_id$OFFSET = $LAYOUT.byteOffset(groupElement("request_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t request_id
     * }
     */
    public static final long request_id$offset() {
        return request_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t request_id
     * }
     */
    public static int request_id(MemorySegment struct) {
        return struct.get(request_id$LAYOUT, request_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t request_id
     * }
     */
    public static void request_id(MemorySegment struct, int fieldValue) {
        struct.set(request_id$LAYOUT, request_id$OFFSET, fieldValue);
    }

    private static final OfInt connection_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("connection_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t connection_id
     * }
     */
    public static final OfInt connection_id$layout() {
        return connection_id$LAYOUT;
    }

    private static final long connection_id$OFFSET = $LAYOUT.byteOffset(groupElement("connection_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t connection_id
     * }
     */
    public static final long connection_id$offset() {
        return connection_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t connection_id
     * }
     */
    public static int connection_id(MemorySegment struct) {
        return struct.get(connection_id$LAYOUT, connection_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t connection_id
     * }
     */
    public static void connection_id(MemorySegment struct, int fieldValue) {
        struct.set(connection_id$LAYOUT, connection_id$OFFSET, fieldValue);
    }

    private static final OfLong connection_server_id$LAYOUT = (OfLong)$LAYOUT.select(groupElement("connection_server_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t connection_server_id
     * }
     */
    public static final OfLong connection_server_id$layout() {
        return connection_server_id$LAYOUT;
    }

    private static final long connection_server_id$OFFSET = $LAYOUT.byteOffset(groupElement("connection_server_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t connection_server_id
     * }
     */
    public static final long connection_server_id$offset() {
        return connection_server_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t connection_server_id
     * }
     */
    public static long connection_server_id(MemorySegment struct) {
        return struct.get(connection_server_id$LAYOUT, connection_server_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t connection_server_id
     * }
     */
    public static void connection_server_id(MemorySegment struct, long fieldValue) {
        struct.set(connection_server_id$LAYOUT, connection_server_id$OFFSET, fieldValue);
    }

    private static final AddressLayout connection_address$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("connection_address"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *connection_address
     * }
     */
    public static final AddressLayout connection_address$layout() {
        return connection_address$LAYOUT;
    }

    private static final long connection_address$OFFSET = $LAYOUT.byteOffset(groupElement("connection_address"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *connection_address
     * }
     */
    public static final long connection_address$offset() {
        return connection_address$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *connection_address
     * }
     */
    public static MemorySegment connection_address(MemorySegment struct) {
        return struct.get(connection_address$LAYOUT, connection_address$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *connection_address
     * }
     */
    public static void connection_address(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(connection_address$LAYOUT, connection_address$OFFSET, fieldValue);
    }

    private static final SequenceLayout service_id$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("service_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t service_id[12]
     * }
     */
    public static final SequenceLayout service_id$layout() {
        return service_id$LAYOUT;
    }

    private static final long service_id$OFFSET = $LAYOUT.byteOffset(groupElement("service_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t service_id[12]
     * }
     */
    public static final long service_id$offset() {
        return service_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t service_id[12]
     * }
     */
    public static MemorySegment service_id(MemorySegment struct) {
        return struct.asSlice(service_id$OFFSET, service_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t service_id[12]
     * }
     */
    public static void service_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, service_id$OFFSET, service_id$LAYOUT.byteSize());
    }

    private static long[] service_id$DIMS = { 12 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t service_id[12]
     * }
     */
    public static long[] service_id$dimensions() {
        return service_id$DIMS;
    }
    private static final VarHandle service_id$ELEM_HANDLE = service_id$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t service_id[12]
     * }
     */
    public static byte service_id(MemorySegment struct, long index0) {
        return (byte)service_id$ELEM_HANDLE.get(struct, service_id$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t service_id[12]
     * }
     */
    public static void service_id(MemorySegment struct, long index0, byte fieldValue) {
        service_id$ELEM_HANDLE.set(struct, service_id$OFFSET, index0, fieldValue);
    }

    private static final OfBoolean has_service_id$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("has_service_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool has_service_id
     * }
     */
    public static final OfBoolean has_service_id$layout() {
        return has_service_id$LAYOUT;
    }

    private static final long has_service_id$OFFSET = $LAYOUT.byteOffset(groupElement("has_service_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool has_service_id
     * }
     */
    public static final long has_service_id$offset() {
        return has_service_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool has_service_id
     * }
     */
    public static boolean has_service_id(MemorySegment struct) {
        return struct.get(has_service_id$LAYOUT, has_service_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool has_service_id
     * }
     */
    public static void has_service_id(MemorySegment struct, boolean fieldValue) {
        struct.set(has_service_id$LAYOUT, has_service_id$OFFSET, fieldValue);
    }

    private static final OfLong duration_nanos$LAYOUT = (OfLong)$LAYOUT.select(groupElement("duration_nanos"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t duration_nanos
     * }
     */
    public static final OfLong duration_nanos$layout() {
        return duration_nanos$LAYOUT;
    }

    private static final long duration_nanos$OFFSET = $LAYOUT.byteOffset(groupElement("duration_nanos"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t duration_nanos
     * }
     */
    public static final long duration_nanos$offset() {
        return duration_nanos$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t duration_nanos
     * }
     */
    public static long duration_nanos(MemorySegment struct) {
        return struct.get(duration_nanos$LAYOUT, duration_nanos$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t duration_nanos
     * }
     */
    public static void duration_nanos(MemorySegment struct, long fieldValue) {
        struct.set(duration_nanos$LAYOUT, duration_nanos$OFFSET, fieldValue);
    }

    private static final AddressLayout failure$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("failure"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Error *failure
     * }
     */
    public static final AddressLayout failure$layout() {
        return failure$LAYOUT;
    }

    private static final long failure$OFFSET = $LAYOUT.byteOffset(groupElement("failure"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Error *failure
     * }
     */
    public static final long failure$offset() {
        return failure$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Error *failure
     * }
     */
    public static MemorySegment failure(MemorySegment struct) {
        return struct.get(failure$LAYOUT, failure$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Error *failure
     * }
     */
    public static void failure(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(failure$LAYOUT, failure$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

