// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct FindOptions {
 *     const struct Bson *projection;
 *     const struct Bson *sort;
 *     int64_t limit;
 *     int64_t skip;
 *     int32_t batch_size;
 *     const struct BsonValue *hint;
 *     const struct Bson *collation;
 *     const struct BsonValue *comment;
 * }
 * }
 */
public class FindOptions {

    FindOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_POINTER.withName("projection"),
        MongoDbFfi.C_POINTER.withName("sort"),
        MongoDbFfi.C_LONG_LONG.withName("limit"),
        MongoDbFfi.C_LONG_LONG.withName("skip"),
        MongoDbFfi.C_INT.withName("batch_size"),
        MemoryLayout.paddingLayout(4),
        MongoDbFfi.C_POINTER.withName("hint"),
        MongoDbFfi.C_POINTER.withName("collation"),
        MongoDbFfi.C_POINTER.withName("comment")
    ).withName("FindOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout projection$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("projection"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static final AddressLayout projection$layout() {
        return projection$LAYOUT;
    }

    private static final long projection$OFFSET = $LAYOUT.byteOffset(groupElement("projection"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static final long projection$offset() {
        return projection$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static MemorySegment projection(MemorySegment struct) {
        return struct.get(projection$LAYOUT, projection$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static void projection(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(projection$LAYOUT, projection$OFFSET, fieldValue);
    }

    private static final AddressLayout sort$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("sort"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static final AddressLayout sort$layout() {
        return sort$LAYOUT;
    }

    private static final long sort$OFFSET = $LAYOUT.byteOffset(groupElement("sort"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static final long sort$offset() {
        return sort$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static MemorySegment sort(MemorySegment struct) {
        return struct.get(sort$LAYOUT, sort$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static void sort(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(sort$LAYOUT, sort$OFFSET, fieldValue);
    }

    private static final OfLong limit$LAYOUT = (OfLong)$LAYOUT.select(groupElement("limit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t limit
     * }
     */
    public static final OfLong limit$layout() {
        return limit$LAYOUT;
    }

    private static final long limit$OFFSET = $LAYOUT.byteOffset(groupElement("limit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t limit
     * }
     */
    public static final long limit$offset() {
        return limit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t limit
     * }
     */
    public static long limit(MemorySegment struct) {
        return struct.get(limit$LAYOUT, limit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t limit
     * }
     */
    public static void limit(MemorySegment struct, long fieldValue) {
        struct.set(limit$LAYOUT, limit$OFFSET, fieldValue);
    }

    private static final OfLong skip$LAYOUT = (OfLong)$LAYOUT.select(groupElement("skip"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t skip
     * }
     */
    public static final OfLong skip$layout() {
        return skip$LAYOUT;
    }

    private static final long skip$OFFSET = $LAYOUT.byteOffset(groupElement("skip"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t skip
     * }
     */
    public static final long skip$offset() {
        return skip$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t skip
     * }
     */
    public static long skip(MemorySegment struct) {
        return struct.get(skip$LAYOUT, skip$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t skip
     * }
     */
    public static void skip(MemorySegment struct, long fieldValue) {
        struct.set(skip$LAYOUT, skip$OFFSET, fieldValue);
    }

    private static final OfInt batch_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("batch_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static final OfInt batch_size$layout() {
        return batch_size$LAYOUT;
    }

    private static final long batch_size$OFFSET = $LAYOUT.byteOffset(groupElement("batch_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static final long batch_size$offset() {
        return batch_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static int batch_size(MemorySegment struct) {
        return struct.get(batch_size$LAYOUT, batch_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static void batch_size(MemorySegment struct, int fieldValue) {
        struct.set(batch_size$LAYOUT, batch_size$OFFSET, fieldValue);
    }

    private static final AddressLayout hint$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("hint"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BsonValue *hint
     * }
     */
    public static final AddressLayout hint$layout() {
        return hint$LAYOUT;
    }

    private static final long hint$OFFSET = $LAYOUT.byteOffset(groupElement("hint"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BsonValue *hint
     * }
     */
    public static final long hint$offset() {
        return hint$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BsonValue *hint
     * }
     */
    public static MemorySegment hint(MemorySegment struct) {
        return struct.get(hint$LAYOUT, hint$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BsonValue *hint
     * }
     */
    public static void hint(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hint$LAYOUT, hint$OFFSET, fieldValue);
    }

    private static final AddressLayout collation$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("collation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final AddressLayout collation$layout() {
        return collation$LAYOUT;
    }

    private static final long collation$OFFSET = $LAYOUT.byteOffset(groupElement("collation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final long collation$offset() {
        return collation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static MemorySegment collation(MemorySegment struct) {
        return struct.get(collation$LAYOUT, collation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static void collation(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(collation$LAYOUT, collation$OFFSET, fieldValue);
    }

    private static final AddressLayout comment$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("comment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final AddressLayout comment$layout() {
        return comment$LAYOUT;
    }

    private static final long comment$OFFSET = $LAYOUT.byteOffset(groupElement("comment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final long comment$offset() {
        return comment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static MemorySegment comment(MemorySegment struct) {
        return struct.get(comment$LAYOUT, comment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static void comment(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(comment$LAYOUT, comment$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

