// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct FindOptions {
 *     int8_t allow_disk_use;
 *     int8_t allow_partial_results;
 *     int32_t batch_size;
 *     const struct Bson *comment;
 *     int8_t cursor_type;
 *     const char *hint_name;
 *     const struct Bson *hint_keys;
 *     int64_t limit;
 *     const struct Bson *max;
 *     int64_t max_await_time_ms;
 *     int64_t max_time_ms;
 *     const struct Bson *min;
 *     int8_t no_cursor_timeout;
 *     const struct Bson *projection;
 *     int8_t return_key;
 *     int8_t show_record_id;
 *     int64_t skip;
 *     const struct Bson *sort;
 *     const struct Bson *collation;
 *     const struct Bson *let_vars;
 * }
 * }
 */
public class FindOptions {

    FindOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_CHAR.withName("allow_disk_use"),
        MongoDbFfi.C_CHAR.withName("allow_partial_results"),
        MemoryLayout.paddingLayout(2),
        MongoDbFfi.C_INT.withName("batch_size"),
        MongoDbFfi.C_POINTER.withName("comment"),
        MongoDbFfi.C_CHAR.withName("cursor_type"),
        MemoryLayout.paddingLayout(7),
        MongoDbFfi.C_POINTER.withName("hint_name"),
        MongoDbFfi.C_POINTER.withName("hint_keys"),
        MongoDbFfi.C_LONG_LONG.withName("limit"),
        MongoDbFfi.C_POINTER.withName("max"),
        MongoDbFfi.C_LONG_LONG.withName("max_await_time_ms"),
        MongoDbFfi.C_LONG_LONG.withName("max_time_ms"),
        MongoDbFfi.C_POINTER.withName("min"),
        MongoDbFfi.C_CHAR.withName("no_cursor_timeout"),
        MemoryLayout.paddingLayout(7),
        MongoDbFfi.C_POINTER.withName("projection"),
        MongoDbFfi.C_CHAR.withName("return_key"),
        MongoDbFfi.C_CHAR.withName("show_record_id"),
        MemoryLayout.paddingLayout(6),
        MongoDbFfi.C_LONG_LONG.withName("skip"),
        MongoDbFfi.C_POINTER.withName("sort"),
        MongoDbFfi.C_POINTER.withName("collation"),
        MongoDbFfi.C_POINTER.withName("let_vars")
    ).withName("FindOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte allow_disk_use$LAYOUT = (OfByte)$LAYOUT.select(groupElement("allow_disk_use"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t allow_disk_use
     * }
     */
    public static final OfByte allow_disk_use$layout() {
        return allow_disk_use$LAYOUT;
    }

    private static final long allow_disk_use$OFFSET = $LAYOUT.byteOffset(groupElement("allow_disk_use"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t allow_disk_use
     * }
     */
    public static final long allow_disk_use$offset() {
        return allow_disk_use$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t allow_disk_use
     * }
     */
    public static byte allow_disk_use(MemorySegment struct) {
        return struct.get(allow_disk_use$LAYOUT, allow_disk_use$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t allow_disk_use
     * }
     */
    public static void allow_disk_use(MemorySegment struct, byte fieldValue) {
        struct.set(allow_disk_use$LAYOUT, allow_disk_use$OFFSET, fieldValue);
    }

    private static final OfByte allow_partial_results$LAYOUT = (OfByte)$LAYOUT.select(groupElement("allow_partial_results"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t allow_partial_results
     * }
     */
    public static final OfByte allow_partial_results$layout() {
        return allow_partial_results$LAYOUT;
    }

    private static final long allow_partial_results$OFFSET = $LAYOUT.byteOffset(groupElement("allow_partial_results"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t allow_partial_results
     * }
     */
    public static final long allow_partial_results$offset() {
        return allow_partial_results$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t allow_partial_results
     * }
     */
    public static byte allow_partial_results(MemorySegment struct) {
        return struct.get(allow_partial_results$LAYOUT, allow_partial_results$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t allow_partial_results
     * }
     */
    public static void allow_partial_results(MemorySegment struct, byte fieldValue) {
        struct.set(allow_partial_results$LAYOUT, allow_partial_results$OFFSET, fieldValue);
    }

    private static final OfInt batch_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("batch_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static final OfInt batch_size$layout() {
        return batch_size$LAYOUT;
    }

    private static final long batch_size$OFFSET = $LAYOUT.byteOffset(groupElement("batch_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static final long batch_size$offset() {
        return batch_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static int batch_size(MemorySegment struct) {
        return struct.get(batch_size$LAYOUT, batch_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t batch_size
     * }
     */
    public static void batch_size(MemorySegment struct, int fieldValue) {
        struct.set(batch_size$LAYOUT, batch_size$OFFSET, fieldValue);
    }

    private static final AddressLayout comment$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("comment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *comment
     * }
     */
    public static final AddressLayout comment$layout() {
        return comment$LAYOUT;
    }

    private static final long comment$OFFSET = $LAYOUT.byteOffset(groupElement("comment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *comment
     * }
     */
    public static final long comment$offset() {
        return comment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *comment
     * }
     */
    public static MemorySegment comment(MemorySegment struct) {
        return struct.get(comment$LAYOUT, comment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *comment
     * }
     */
    public static void comment(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(comment$LAYOUT, comment$OFFSET, fieldValue);
    }

    private static final OfByte cursor_type$LAYOUT = (OfByte)$LAYOUT.select(groupElement("cursor_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t cursor_type
     * }
     */
    public static final OfByte cursor_type$layout() {
        return cursor_type$LAYOUT;
    }

    private static final long cursor_type$OFFSET = $LAYOUT.byteOffset(groupElement("cursor_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t cursor_type
     * }
     */
    public static final long cursor_type$offset() {
        return cursor_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t cursor_type
     * }
     */
    public static byte cursor_type(MemorySegment struct) {
        return struct.get(cursor_type$LAYOUT, cursor_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t cursor_type
     * }
     */
    public static void cursor_type(MemorySegment struct, byte fieldValue) {
        struct.set(cursor_type$LAYOUT, cursor_type$OFFSET, fieldValue);
    }

    private static final AddressLayout hint_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("hint_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *hint_name
     * }
     */
    public static final AddressLayout hint_name$layout() {
        return hint_name$LAYOUT;
    }

    private static final long hint_name$OFFSET = $LAYOUT.byteOffset(groupElement("hint_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *hint_name
     * }
     */
    public static final long hint_name$offset() {
        return hint_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *hint_name
     * }
     */
    public static MemorySegment hint_name(MemorySegment struct) {
        return struct.get(hint_name$LAYOUT, hint_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *hint_name
     * }
     */
    public static void hint_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hint_name$LAYOUT, hint_name$OFFSET, fieldValue);
    }

    private static final AddressLayout hint_keys$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("hint_keys"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *hint_keys
     * }
     */
    public static final AddressLayout hint_keys$layout() {
        return hint_keys$LAYOUT;
    }

    private static final long hint_keys$OFFSET = $LAYOUT.byteOffset(groupElement("hint_keys"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *hint_keys
     * }
     */
    public static final long hint_keys$offset() {
        return hint_keys$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *hint_keys
     * }
     */
    public static MemorySegment hint_keys(MemorySegment struct) {
        return struct.get(hint_keys$LAYOUT, hint_keys$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *hint_keys
     * }
     */
    public static void hint_keys(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hint_keys$LAYOUT, hint_keys$OFFSET, fieldValue);
    }

    private static final OfLong limit$LAYOUT = (OfLong)$LAYOUT.select(groupElement("limit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t limit
     * }
     */
    public static final OfLong limit$layout() {
        return limit$LAYOUT;
    }

    private static final long limit$OFFSET = $LAYOUT.byteOffset(groupElement("limit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t limit
     * }
     */
    public static final long limit$offset() {
        return limit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t limit
     * }
     */
    public static long limit(MemorySegment struct) {
        return struct.get(limit$LAYOUT, limit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t limit
     * }
     */
    public static void limit(MemorySegment struct, long fieldValue) {
        struct.set(limit$LAYOUT, limit$OFFSET, fieldValue);
    }

    private static final AddressLayout max$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("max"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *max
     * }
     */
    public static final AddressLayout max$layout() {
        return max$LAYOUT;
    }

    private static final long max$OFFSET = $LAYOUT.byteOffset(groupElement("max"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *max
     * }
     */
    public static final long max$offset() {
        return max$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *max
     * }
     */
    public static MemorySegment max(MemorySegment struct) {
        return struct.get(max$LAYOUT, max$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *max
     * }
     */
    public static void max(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(max$LAYOUT, max$OFFSET, fieldValue);
    }

    private static final OfLong max_await_time_ms$LAYOUT = (OfLong)$LAYOUT.select(groupElement("max_await_time_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t max_await_time_ms
     * }
     */
    public static final OfLong max_await_time_ms$layout() {
        return max_await_time_ms$LAYOUT;
    }

    private static final long max_await_time_ms$OFFSET = $LAYOUT.byteOffset(groupElement("max_await_time_ms"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t max_await_time_ms
     * }
     */
    public static final long max_await_time_ms$offset() {
        return max_await_time_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t max_await_time_ms
     * }
     */
    public static long max_await_time_ms(MemorySegment struct) {
        return struct.get(max_await_time_ms$LAYOUT, max_await_time_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t max_await_time_ms
     * }
     */
    public static void max_await_time_ms(MemorySegment struct, long fieldValue) {
        struct.set(max_await_time_ms$LAYOUT, max_await_time_ms$OFFSET, fieldValue);
    }

    private static final OfLong max_time_ms$LAYOUT = (OfLong)$LAYOUT.select(groupElement("max_time_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t max_time_ms
     * }
     */
    public static final OfLong max_time_ms$layout() {
        return max_time_ms$LAYOUT;
    }

    private static final long max_time_ms$OFFSET = $LAYOUT.byteOffset(groupElement("max_time_ms"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t max_time_ms
     * }
     */
    public static final long max_time_ms$offset() {
        return max_time_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t max_time_ms
     * }
     */
    public static long max_time_ms(MemorySegment struct) {
        return struct.get(max_time_ms$LAYOUT, max_time_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t max_time_ms
     * }
     */
    public static void max_time_ms(MemorySegment struct, long fieldValue) {
        struct.set(max_time_ms$LAYOUT, max_time_ms$OFFSET, fieldValue);
    }

    private static final AddressLayout min$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("min"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *min
     * }
     */
    public static final AddressLayout min$layout() {
        return min$LAYOUT;
    }

    private static final long min$OFFSET = $LAYOUT.byteOffset(groupElement("min"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *min
     * }
     */
    public static final long min$offset() {
        return min$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *min
     * }
     */
    public static MemorySegment min(MemorySegment struct) {
        return struct.get(min$LAYOUT, min$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *min
     * }
     */
    public static void min(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(min$LAYOUT, min$OFFSET, fieldValue);
    }

    private static final OfByte no_cursor_timeout$LAYOUT = (OfByte)$LAYOUT.select(groupElement("no_cursor_timeout"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t no_cursor_timeout
     * }
     */
    public static final OfByte no_cursor_timeout$layout() {
        return no_cursor_timeout$LAYOUT;
    }

    private static final long no_cursor_timeout$OFFSET = $LAYOUT.byteOffset(groupElement("no_cursor_timeout"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t no_cursor_timeout
     * }
     */
    public static final long no_cursor_timeout$offset() {
        return no_cursor_timeout$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t no_cursor_timeout
     * }
     */
    public static byte no_cursor_timeout(MemorySegment struct) {
        return struct.get(no_cursor_timeout$LAYOUT, no_cursor_timeout$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t no_cursor_timeout
     * }
     */
    public static void no_cursor_timeout(MemorySegment struct, byte fieldValue) {
        struct.set(no_cursor_timeout$LAYOUT, no_cursor_timeout$OFFSET, fieldValue);
    }

    private static final AddressLayout projection$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("projection"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static final AddressLayout projection$layout() {
        return projection$LAYOUT;
    }

    private static final long projection$OFFSET = $LAYOUT.byteOffset(groupElement("projection"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static final long projection$offset() {
        return projection$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static MemorySegment projection(MemorySegment struct) {
        return struct.get(projection$LAYOUT, projection$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static void projection(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(projection$LAYOUT, projection$OFFSET, fieldValue);
    }

    private static final OfByte return_key$LAYOUT = (OfByte)$LAYOUT.select(groupElement("return_key"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t return_key
     * }
     */
    public static final OfByte return_key$layout() {
        return return_key$LAYOUT;
    }

    private static final long return_key$OFFSET = $LAYOUT.byteOffset(groupElement("return_key"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t return_key
     * }
     */
    public static final long return_key$offset() {
        return return_key$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t return_key
     * }
     */
    public static byte return_key(MemorySegment struct) {
        return struct.get(return_key$LAYOUT, return_key$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t return_key
     * }
     */
    public static void return_key(MemorySegment struct, byte fieldValue) {
        struct.set(return_key$LAYOUT, return_key$OFFSET, fieldValue);
    }

    private static final OfByte show_record_id$LAYOUT = (OfByte)$LAYOUT.select(groupElement("show_record_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t show_record_id
     * }
     */
    public static final OfByte show_record_id$layout() {
        return show_record_id$LAYOUT;
    }

    private static final long show_record_id$OFFSET = $LAYOUT.byteOffset(groupElement("show_record_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t show_record_id
     * }
     */
    public static final long show_record_id$offset() {
        return show_record_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t show_record_id
     * }
     */
    public static byte show_record_id(MemorySegment struct) {
        return struct.get(show_record_id$LAYOUT, show_record_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t show_record_id
     * }
     */
    public static void show_record_id(MemorySegment struct, byte fieldValue) {
        struct.set(show_record_id$LAYOUT, show_record_id$OFFSET, fieldValue);
    }

    private static final OfLong skip$LAYOUT = (OfLong)$LAYOUT.select(groupElement("skip"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t skip
     * }
     */
    public static final OfLong skip$layout() {
        return skip$LAYOUT;
    }

    private static final long skip$OFFSET = $LAYOUT.byteOffset(groupElement("skip"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t skip
     * }
     */
    public static final long skip$offset() {
        return skip$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t skip
     * }
     */
    public static long skip(MemorySegment struct) {
        return struct.get(skip$LAYOUT, skip$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t skip
     * }
     */
    public static void skip(MemorySegment struct, long fieldValue) {
        struct.set(skip$LAYOUT, skip$OFFSET, fieldValue);
    }

    private static final AddressLayout sort$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("sort"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static final AddressLayout sort$layout() {
        return sort$LAYOUT;
    }

    private static final long sort$OFFSET = $LAYOUT.byteOffset(groupElement("sort"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static final long sort$offset() {
        return sort$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static MemorySegment sort(MemorySegment struct) {
        return struct.get(sort$LAYOUT, sort$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static void sort(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(sort$LAYOUT, sort$OFFSET, fieldValue);
    }

    private static final AddressLayout collation$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("collation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final AddressLayout collation$layout() {
        return collation$LAYOUT;
    }

    private static final long collation$OFFSET = $LAYOUT.byteOffset(groupElement("collation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final long collation$offset() {
        return collation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static MemorySegment collation(MemorySegment struct) {
        return struct.get(collation$LAYOUT, collation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static void collation(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(collation$LAYOUT, collation$OFFSET, fieldValue);
    }

    private static final AddressLayout let_vars$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("let_vars"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *let_vars
     * }
     */
    public static final AddressLayout let_vars$layout() {
        return let_vars$LAYOUT;
    }

    private static final long let_vars$OFFSET = $LAYOUT.byteOffset(groupElement("let_vars"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *let_vars
     * }
     */
    public static final long let_vars$offset() {
        return let_vars$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *let_vars
     * }
     */
    public static MemorySegment let_vars(MemorySegment struct) {
        return struct.get(let_vars$LAYOUT, let_vars$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *let_vars
     * }
     */
    public static void let_vars(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(let_vars$LAYOUT, let_vars$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

