// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct FindOneAndDeleteOptions {
 *     const struct Bson *projection;
 *     const struct Bson *sort;
 *     const struct BsonValue *hint;
 *     const struct Bson *collation;
 *     const struct BsonValue *comment;
 * }
 * }
 */
public class FindOneAndDeleteOptions {

    FindOneAndDeleteOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_POINTER.withName("projection"),
        MongoDbFfi.C_POINTER.withName("sort"),
        MongoDbFfi.C_POINTER.withName("hint"),
        MongoDbFfi.C_POINTER.withName("collation"),
        MongoDbFfi.C_POINTER.withName("comment")
    ).withName("FindOneAndDeleteOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout projection$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("projection"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static final AddressLayout projection$layout() {
        return projection$LAYOUT;
    }

    private static final long projection$OFFSET = $LAYOUT.byteOffset(groupElement("projection"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static final long projection$offset() {
        return projection$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static MemorySegment projection(MemorySegment struct) {
        return struct.get(projection$LAYOUT, projection$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static void projection(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(projection$LAYOUT, projection$OFFSET, fieldValue);
    }

    private static final AddressLayout sort$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("sort"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static final AddressLayout sort$layout() {
        return sort$LAYOUT;
    }

    private static final long sort$OFFSET = $LAYOUT.byteOffset(groupElement("sort"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static final long sort$offset() {
        return sort$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static MemorySegment sort(MemorySegment struct) {
        return struct.get(sort$LAYOUT, sort$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static void sort(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(sort$LAYOUT, sort$OFFSET, fieldValue);
    }

    private static final AddressLayout hint$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("hint"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BsonValue *hint
     * }
     */
    public static final AddressLayout hint$layout() {
        return hint$LAYOUT;
    }

    private static final long hint$OFFSET = $LAYOUT.byteOffset(groupElement("hint"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BsonValue *hint
     * }
     */
    public static final long hint$offset() {
        return hint$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BsonValue *hint
     * }
     */
    public static MemorySegment hint(MemorySegment struct) {
        return struct.get(hint$LAYOUT, hint$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BsonValue *hint
     * }
     */
    public static void hint(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hint$LAYOUT, hint$OFFSET, fieldValue);
    }

    private static final AddressLayout collation$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("collation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final AddressLayout collation$layout() {
        return collation$LAYOUT;
    }

    private static final long collation$OFFSET = $LAYOUT.byteOffset(groupElement("collation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final long collation$offset() {
        return collation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static MemorySegment collation(MemorySegment struct) {
        return struct.get(collation$LAYOUT, collation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static void collation(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(collation$LAYOUT, collation$OFFSET, fieldValue);
    }

    private static final AddressLayout comment$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("comment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final AddressLayout comment$layout() {
        return comment$LAYOUT;
    }

    private static final long comment$OFFSET = $LAYOUT.byteOffset(groupElement("comment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final long comment$offset() {
        return comment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static MemorySegment comment(MemorySegment struct) {
        return struct.get(comment$LAYOUT, comment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static void comment(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(comment$LAYOUT, comment$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

