// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct FindOneAndUpdateOptions {
 *     struct BsonArray array_filters;
 *     int8_t bypass_document_validation;
 *     int64_t max_time_ms;
 *     const struct Bson *projection;
 *     int8_t return_document;
 *     const struct Bson *sort;
 *     int8_t upsert;
 *     const struct Bson *collation;
 *     const char *hint_name;
 *     const struct Bson *hint_keys;
 *     const struct Bson *let_vars;
 *     const struct BsonValue *comment;
 * }
 * }
 */
public class FindOneAndUpdateOptions {

    FindOneAndUpdateOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        BsonArray.layout().withName("array_filters"),
        MongoDbFfi.C_CHAR.withName("bypass_document_validation"),
        MemoryLayout.paddingLayout(7),
        MongoDbFfi.C_LONG_LONG.withName("max_time_ms"),
        MongoDbFfi.C_POINTER.withName("projection"),
        MongoDbFfi.C_CHAR.withName("return_document"),
        MemoryLayout.paddingLayout(7),
        MongoDbFfi.C_POINTER.withName("sort"),
        MongoDbFfi.C_CHAR.withName("upsert"),
        MemoryLayout.paddingLayout(7),
        MongoDbFfi.C_POINTER.withName("collation"),
        MongoDbFfi.C_POINTER.withName("hint_name"),
        MongoDbFfi.C_POINTER.withName("hint_keys"),
        MongoDbFfi.C_POINTER.withName("let_vars"),
        MongoDbFfi.C_POINTER.withName("comment")
    ).withName("FindOneAndUpdateOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout array_filters$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("array_filters"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct BsonArray array_filters
     * }
     */
    public static final GroupLayout array_filters$layout() {
        return array_filters$LAYOUT;
    }

    private static final long array_filters$OFFSET = $LAYOUT.byteOffset(groupElement("array_filters"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct BsonArray array_filters
     * }
     */
    public static final long array_filters$offset() {
        return array_filters$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct BsonArray array_filters
     * }
     */
    public static MemorySegment array_filters(MemorySegment struct) {
        return struct.asSlice(array_filters$OFFSET, array_filters$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct BsonArray array_filters
     * }
     */
    public static void array_filters(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, array_filters$OFFSET, array_filters$LAYOUT.byteSize());
    }

    private static final OfByte bypass_document_validation$LAYOUT = (OfByte)$LAYOUT.select(groupElement("bypass_document_validation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static final OfByte bypass_document_validation$layout() {
        return bypass_document_validation$LAYOUT;
    }

    private static final long bypass_document_validation$OFFSET = $LAYOUT.byteOffset(groupElement("bypass_document_validation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static final long bypass_document_validation$offset() {
        return bypass_document_validation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static byte bypass_document_validation(MemorySegment struct) {
        return struct.get(bypass_document_validation$LAYOUT, bypass_document_validation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static void bypass_document_validation(MemorySegment struct, byte fieldValue) {
        struct.set(bypass_document_validation$LAYOUT, bypass_document_validation$OFFSET, fieldValue);
    }

    private static final OfLong max_time_ms$LAYOUT = (OfLong)$LAYOUT.select(groupElement("max_time_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t max_time_ms
     * }
     */
    public static final OfLong max_time_ms$layout() {
        return max_time_ms$LAYOUT;
    }

    private static final long max_time_ms$OFFSET = $LAYOUT.byteOffset(groupElement("max_time_ms"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t max_time_ms
     * }
     */
    public static final long max_time_ms$offset() {
        return max_time_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t max_time_ms
     * }
     */
    public static long max_time_ms(MemorySegment struct) {
        return struct.get(max_time_ms$LAYOUT, max_time_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t max_time_ms
     * }
     */
    public static void max_time_ms(MemorySegment struct, long fieldValue) {
        struct.set(max_time_ms$LAYOUT, max_time_ms$OFFSET, fieldValue);
    }

    private static final AddressLayout projection$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("projection"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static final AddressLayout projection$layout() {
        return projection$LAYOUT;
    }

    private static final long projection$OFFSET = $LAYOUT.byteOffset(groupElement("projection"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static final long projection$offset() {
        return projection$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static MemorySegment projection(MemorySegment struct) {
        return struct.get(projection$LAYOUT, projection$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *projection
     * }
     */
    public static void projection(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(projection$LAYOUT, projection$OFFSET, fieldValue);
    }

    private static final OfByte return_document$LAYOUT = (OfByte)$LAYOUT.select(groupElement("return_document"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t return_document
     * }
     */
    public static final OfByte return_document$layout() {
        return return_document$LAYOUT;
    }

    private static final long return_document$OFFSET = $LAYOUT.byteOffset(groupElement("return_document"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t return_document
     * }
     */
    public static final long return_document$offset() {
        return return_document$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t return_document
     * }
     */
    public static byte return_document(MemorySegment struct) {
        return struct.get(return_document$LAYOUT, return_document$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t return_document
     * }
     */
    public static void return_document(MemorySegment struct, byte fieldValue) {
        struct.set(return_document$LAYOUT, return_document$OFFSET, fieldValue);
    }

    private static final AddressLayout sort$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("sort"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static final AddressLayout sort$layout() {
        return sort$LAYOUT;
    }

    private static final long sort$OFFSET = $LAYOUT.byteOffset(groupElement("sort"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static final long sort$offset() {
        return sort$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static MemorySegment sort(MemorySegment struct) {
        return struct.get(sort$LAYOUT, sort$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *sort
     * }
     */
    public static void sort(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(sort$LAYOUT, sort$OFFSET, fieldValue);
    }

    private static final OfByte upsert$LAYOUT = (OfByte)$LAYOUT.select(groupElement("upsert"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t upsert
     * }
     */
    public static final OfByte upsert$layout() {
        return upsert$LAYOUT;
    }

    private static final long upsert$OFFSET = $LAYOUT.byteOffset(groupElement("upsert"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t upsert
     * }
     */
    public static final long upsert$offset() {
        return upsert$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t upsert
     * }
     */
    public static byte upsert(MemorySegment struct) {
        return struct.get(upsert$LAYOUT, upsert$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t upsert
     * }
     */
    public static void upsert(MemorySegment struct, byte fieldValue) {
        struct.set(upsert$LAYOUT, upsert$OFFSET, fieldValue);
    }

    private static final AddressLayout collation$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("collation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final AddressLayout collation$layout() {
        return collation$LAYOUT;
    }

    private static final long collation$OFFSET = $LAYOUT.byteOffset(groupElement("collation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final long collation$offset() {
        return collation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static MemorySegment collation(MemorySegment struct) {
        return struct.get(collation$LAYOUT, collation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static void collation(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(collation$LAYOUT, collation$OFFSET, fieldValue);
    }

    private static final AddressLayout hint_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("hint_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *hint_name
     * }
     */
    public static final AddressLayout hint_name$layout() {
        return hint_name$LAYOUT;
    }

    private static final long hint_name$OFFSET = $LAYOUT.byteOffset(groupElement("hint_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *hint_name
     * }
     */
    public static final long hint_name$offset() {
        return hint_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *hint_name
     * }
     */
    public static MemorySegment hint_name(MemorySegment struct) {
        return struct.get(hint_name$LAYOUT, hint_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *hint_name
     * }
     */
    public static void hint_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hint_name$LAYOUT, hint_name$OFFSET, fieldValue);
    }

    private static final AddressLayout hint_keys$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("hint_keys"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *hint_keys
     * }
     */
    public static final AddressLayout hint_keys$layout() {
        return hint_keys$LAYOUT;
    }

    private static final long hint_keys$OFFSET = $LAYOUT.byteOffset(groupElement("hint_keys"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *hint_keys
     * }
     */
    public static final long hint_keys$offset() {
        return hint_keys$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *hint_keys
     * }
     */
    public static MemorySegment hint_keys(MemorySegment struct) {
        return struct.get(hint_keys$LAYOUT, hint_keys$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *hint_keys
     * }
     */
    public static void hint_keys(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hint_keys$LAYOUT, hint_keys$OFFSET, fieldValue);
    }

    private static final AddressLayout let_vars$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("let_vars"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *let_vars
     * }
     */
    public static final AddressLayout let_vars$layout() {
        return let_vars$LAYOUT;
    }

    private static final long let_vars$OFFSET = $LAYOUT.byteOffset(groupElement("let_vars"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *let_vars
     * }
     */
    public static final long let_vars$offset() {
        return let_vars$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *let_vars
     * }
     */
    public static MemorySegment let_vars(MemorySegment struct) {
        return struct.get(let_vars$LAYOUT, let_vars$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *let_vars
     * }
     */
    public static void let_vars(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(let_vars$LAYOUT, let_vars$OFFSET, fieldValue);
    }

    private static final AddressLayout comment$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("comment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final AddressLayout comment$layout() {
        return comment$LAYOUT;
    }

    private static final long comment$OFFSET = $LAYOUT.byteOffset(groupElement("comment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final long comment$offset() {
        return comment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static MemorySegment comment(MemorySegment struct) {
        return struct.get(comment$LAYOUT, comment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static void comment(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(comment$LAYOUT, comment$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

