// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*GetMoreResultCallback)(void *, bool, struct BsonArray {
 *     const uint8_t *const *data;
 *     size_t len;
 * }, const struct Error {
 *     uint8_t error_type;
 *     union ErrorUnion error;
 * } *)
 * }
 */
public final class GetMoreResultCallback {

    private GetMoreResultCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment userdata, boolean exhausted, MemorySegment data, MemorySegment error);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        MongoDbFfi.C_POINTER,
        MongoDbFfi.C_BOOL,
        BsonArray.layout(),
        MongoDbFfi.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = MongoDbFfi.upcallHandle(GetMoreResultCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(GetMoreResultCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment userdata, boolean exhausted, MemorySegment data, MemorySegment error) {
        try {
             DOWN$MH.invokeExact(funcPtr, userdata, exhausted, data, error);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

