// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct InsertManyResult {
 *     const struct InsertedId *inserted_ids;
 *     size_t inserted_ids_len;
 * }
 * }
 */
public class InsertManyResult {

    InsertManyResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_POINTER.withName("inserted_ids"),
        MongoDbFfi.C_LONG.withName("inserted_ids_len")
    ).withName("InsertManyResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout inserted_ids$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("inserted_ids"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct InsertedId *inserted_ids
     * }
     */
    public static final AddressLayout inserted_ids$layout() {
        return inserted_ids$LAYOUT;
    }

    private static final long inserted_ids$OFFSET = $LAYOUT.byteOffset(groupElement("inserted_ids"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct InsertedId *inserted_ids
     * }
     */
    public static final long inserted_ids$offset() {
        return inserted_ids$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct InsertedId *inserted_ids
     * }
     */
    public static MemorySegment inserted_ids(MemorySegment struct) {
        return struct.get(inserted_ids$LAYOUT, inserted_ids$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct InsertedId *inserted_ids
     * }
     */
    public static void inserted_ids(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(inserted_ids$LAYOUT, inserted_ids$OFFSET, fieldValue);
    }

    private static final OfLong inserted_ids_len$LAYOUT = (OfLong)$LAYOUT.select(groupElement("inserted_ids_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t inserted_ids_len
     * }
     */
    public static final OfLong inserted_ids_len$layout() {
        return inserted_ids_len$LAYOUT;
    }

    private static final long inserted_ids_len$OFFSET = $LAYOUT.byteOffset(groupElement("inserted_ids_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t inserted_ids_len
     * }
     */
    public static final long inserted_ids_len$offset() {
        return inserted_ids_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t inserted_ids_len
     * }
     */
    public static long inserted_ids_len(MemorySegment struct) {
        return struct.get(inserted_ids_len$LAYOUT, inserted_ids_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t inserted_ids_len
     * }
     */
    public static void inserted_ids_len(MemorySegment struct, long fieldValue) {
        struct.set(inserted_ids_len$LAYOUT, inserted_ids_len$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

