// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct InsertOneResult {
 *     struct BsonValue inserted_id;
 * }
 * }
 */
public class InsertOneResult {

    InsertOneResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        BsonValue.layout().withName("inserted_id")
    ).withName("InsertOneResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout inserted_id$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("inserted_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct BsonValue inserted_id
     * }
     */
    public static final GroupLayout inserted_id$layout() {
        return inserted_id$LAYOUT;
    }

    private static final long inserted_id$OFFSET = $LAYOUT.byteOffset(groupElement("inserted_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct BsonValue inserted_id
     * }
     */
    public static final long inserted_id$offset() {
        return inserted_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct BsonValue inserted_id
     * }
     */
    public static MemorySegment inserted_id(MemorySegment struct) {
        return struct.asSlice(inserted_id$OFFSET, inserted_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct BsonValue inserted_id
     * }
     */
    public static void inserted_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, inserted_id$OFFSET, inserted_id$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

