// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct InsertManyOptions {
 *     int8_t bypass_document_validation;
 *     int8_t ordered;
 *     const struct BsonValue *comment;
 * }
 * }
 */
public class InsertManyOptions {

    InsertManyOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_CHAR.withName("bypass_document_validation"),
        MongoDbFfi.C_CHAR.withName("ordered"),
        MemoryLayout.paddingLayout(6),
        MongoDbFfi.C_POINTER.withName("comment")
    ).withName("InsertManyOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte bypass_document_validation$LAYOUT = (OfByte)$LAYOUT.select(groupElement("bypass_document_validation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static final OfByte bypass_document_validation$layout() {
        return bypass_document_validation$LAYOUT;
    }

    private static final long bypass_document_validation$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static final long bypass_document_validation$offset() {
        return bypass_document_validation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static byte bypass_document_validation(MemorySegment struct) {
        return struct.get(bypass_document_validation$LAYOUT, bypass_document_validation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static void bypass_document_validation(MemorySegment struct, byte fieldValue) {
        struct.set(bypass_document_validation$LAYOUT, bypass_document_validation$OFFSET, fieldValue);
    }

    private static final OfByte ordered$LAYOUT = (OfByte)$LAYOUT.select(groupElement("ordered"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t ordered
     * }
     */
    public static final OfByte ordered$layout() {
        return ordered$LAYOUT;
    }

    private static final long ordered$OFFSET = 1;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t ordered
     * }
     */
    public static final long ordered$offset() {
        return ordered$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t ordered
     * }
     */
    public static byte ordered(MemorySegment struct) {
        return struct.get(ordered$LAYOUT, ordered$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t ordered
     * }
     */
    public static void ordered(MemorySegment struct, byte fieldValue) {
        struct.set(ordered$LAYOUT, ordered$OFFSET, fieldValue);
    }

    private static final AddressLayout comment$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("comment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final AddressLayout comment$layout() {
        return comment$LAYOUT;
    }

    private static final long comment$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final long comment$offset() {
        return comment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static MemorySegment comment(MemorySegment struct) {
        return struct.get(comment$LAYOUT, comment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static void comment(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(comment$LAYOUT, comment$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

