// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ListDatabasesOptions {
 *     const struct Bson *filter;
 *     int8_t name_only;
 *     int8_t authorized_databases;
 *     const struct BsonValue *comment;
 * }
 * }
 */
public class ListDatabasesOptions {

    ListDatabasesOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_POINTER.withName("filter"),
        MongoDbFfi.C_CHAR.withName("name_only"),
        MongoDbFfi.C_CHAR.withName("authorized_databases"),
        MemoryLayout.paddingLayout(6),
        MongoDbFfi.C_POINTER.withName("comment")
    ).withName("ListDatabasesOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout filter$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("filter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *filter
     * }
     */
    public static final AddressLayout filter$layout() {
        return filter$LAYOUT;
    }

    private static final long filter$OFFSET = $LAYOUT.byteOffset(groupElement("filter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *filter
     * }
     */
    public static final long filter$offset() {
        return filter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *filter
     * }
     */
    public static MemorySegment filter(MemorySegment struct) {
        return struct.get(filter$LAYOUT, filter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *filter
     * }
     */
    public static void filter(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(filter$LAYOUT, filter$OFFSET, fieldValue);
    }

    private static final OfByte name_only$LAYOUT = (OfByte)$LAYOUT.select(groupElement("name_only"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t name_only
     * }
     */
    public static final OfByte name_only$layout() {
        return name_only$LAYOUT;
    }

    private static final long name_only$OFFSET = $LAYOUT.byteOffset(groupElement("name_only"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t name_only
     * }
     */
    public static final long name_only$offset() {
        return name_only$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t name_only
     * }
     */
    public static byte name_only(MemorySegment struct) {
        return struct.get(name_only$LAYOUT, name_only$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t name_only
     * }
     */
    public static void name_only(MemorySegment struct, byte fieldValue) {
        struct.set(name_only$LAYOUT, name_only$OFFSET, fieldValue);
    }

    private static final OfByte authorized_databases$LAYOUT = (OfByte)$LAYOUT.select(groupElement("authorized_databases"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t authorized_databases
     * }
     */
    public static final OfByte authorized_databases$layout() {
        return authorized_databases$LAYOUT;
    }

    private static final long authorized_databases$OFFSET = $LAYOUT.byteOffset(groupElement("authorized_databases"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t authorized_databases
     * }
     */
    public static final long authorized_databases$offset() {
        return authorized_databases$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t authorized_databases
     * }
     */
    public static byte authorized_databases(MemorySegment struct) {
        return struct.get(authorized_databases$LAYOUT, authorized_databases$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t authorized_databases
     * }
     */
    public static void authorized_databases(MemorySegment struct, byte fieldValue) {
        struct.set(authorized_databases$LAYOUT, authorized_databases$OFFSET, fieldValue);
    }

    private static final AddressLayout comment$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("comment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final AddressLayout comment$layout() {
        return comment$LAYOUT;
    }

    private static final long comment$OFFSET = $LAYOUT.byteOffset(groupElement("comment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final long comment$offset() {
        return comment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static MemorySegment comment(MemorySegment struct) {
        return struct.get(comment$LAYOUT, comment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static void comment(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(comment$LAYOUT, comment$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

