// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct MongoCommandEventHandler {
 *     void (*started)(void *, const struct FfiCommandStartedEvent *);
 *     void (*succeeded)(void *, const struct FfiCommandSucceededEvent *);
 *     void (*failed)(void *, const struct FfiCommandFailedEvent *);
 *     void *userdata;
 * }
 * }
 */
public class MongoCommandEventHandler {

    MongoCommandEventHandler() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_POINTER.withName("started"),
        MongoDbFfi.C_POINTER.withName("succeeded"),
        MongoDbFfi.C_POINTER.withName("failed"),
        MongoDbFfi.C_POINTER.withName("userdata")
    ).withName("MongoCommandEventHandler");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * {@snippet lang=c :
     * void (*started)(void *, const struct FfiCommandStartedEvent *)
     * }
     */
    public final static class started {

        private started() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            MongoDbFfi.C_POINTER,
            MongoDbFfi.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = MongoDbFfi.upcallHandle(started.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(started.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout started$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("started"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*started)(void *, const struct FfiCommandStartedEvent *)
     * }
     */
    public static final AddressLayout started$layout() {
        return started$LAYOUT;
    }

    private static final long started$OFFSET = $LAYOUT.byteOffset(groupElement("started"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*started)(void *, const struct FfiCommandStartedEvent *)
     * }
     */
    public static final long started$offset() {
        return started$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*started)(void *, const struct FfiCommandStartedEvent *)
     * }
     */
    public static MemorySegment started(MemorySegment struct) {
        return struct.get(started$LAYOUT, started$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*started)(void *, const struct FfiCommandStartedEvent *)
     * }
     */
    public static void started(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(started$LAYOUT, started$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*succeeded)(void *, const struct FfiCommandSucceededEvent *)
     * }
     */
    public final static class succeeded {

        private succeeded() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            MongoDbFfi.C_POINTER,
            MongoDbFfi.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = MongoDbFfi.upcallHandle(succeeded.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(succeeded.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout succeeded$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("succeeded"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*succeeded)(void *, const struct FfiCommandSucceededEvent *)
     * }
     */
    public static final AddressLayout succeeded$layout() {
        return succeeded$LAYOUT;
    }

    private static final long succeeded$OFFSET = $LAYOUT.byteOffset(groupElement("succeeded"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*succeeded)(void *, const struct FfiCommandSucceededEvent *)
     * }
     */
    public static final long succeeded$offset() {
        return succeeded$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*succeeded)(void *, const struct FfiCommandSucceededEvent *)
     * }
     */
    public static MemorySegment succeeded(MemorySegment struct) {
        return struct.get(succeeded$LAYOUT, succeeded$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*succeeded)(void *, const struct FfiCommandSucceededEvent *)
     * }
     */
    public static void succeeded(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(succeeded$LAYOUT, succeeded$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*failed)(void *, const struct FfiCommandFailedEvent *)
     * }
     */
    public final static class failed {

        private failed() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            MongoDbFfi.C_POINTER,
            MongoDbFfi.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = MongoDbFfi.upcallHandle(failed.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(failed.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout failed$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("failed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*failed)(void *, const struct FfiCommandFailedEvent *)
     * }
     */
    public static final AddressLayout failed$layout() {
        return failed$LAYOUT;
    }

    private static final long failed$OFFSET = $LAYOUT.byteOffset(groupElement("failed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*failed)(void *, const struct FfiCommandFailedEvent *)
     * }
     */
    public static final long failed$offset() {
        return failed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*failed)(void *, const struct FfiCommandFailedEvent *)
     * }
     */
    public static MemorySegment failed(MemorySegment struct) {
        return struct.get(failed$LAYOUT, failed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*failed)(void *, const struct FfiCommandFailedEvent *)
     * }
     */
    public static void failed(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(failed$LAYOUT, failed$OFFSET, fieldValue);
    }

    private static final AddressLayout userdata$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("userdata"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *userdata
     * }
     */
    public static final AddressLayout userdata$layout() {
        return userdata$LAYOUT;
    }

    private static final long userdata$OFFSET = $LAYOUT.byteOffset(groupElement("userdata"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *userdata
     * }
     */
    public static final long userdata$offset() {
        return userdata$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *userdata
     * }
     */
    public static MemorySegment userdata(MemorySegment struct) {
        return struct.get(userdata$LAYOUT, userdata$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *userdata
     * }
     */
    public static void userdata(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(userdata$LAYOUT, userdata$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

