// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OperationContext {
 *     const struct Session *session;
 *     const struct ReadPreference *read_preference;
 *     const struct WriteConcern *write_concern;
 *     const struct ReadConcern *read_concern;
 *     int64_t timeout_ms;
 * }
 * }
 */
public class OperationContext {

    OperationContext() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_POINTER.withName("session"),
        MongoDbFfi.C_POINTER.withName("read_preference"),
        MongoDbFfi.C_POINTER.withName("write_concern"),
        MongoDbFfi.C_POINTER.withName("read_concern"),
        MongoDbFfi.C_LONG_LONG.withName("timeout_ms")
    ).withName("OperationContext");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout session$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("session"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Session *session
     * }
     */
    public static final AddressLayout session$layout() {
        return session$LAYOUT;
    }

    private static final long session$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Session *session
     * }
     */
    public static final long session$offset() {
        return session$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Session *session
     * }
     */
    public static MemorySegment session(MemorySegment struct) {
        return struct.get(session$LAYOUT, session$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Session *session
     * }
     */
    public static void session(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(session$LAYOUT, session$OFFSET, fieldValue);
    }

    private static final AddressLayout read_preference$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("read_preference"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct ReadPreference *read_preference
     * }
     */
    public static final AddressLayout read_preference$layout() {
        return read_preference$LAYOUT;
    }

    private static final long read_preference$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct ReadPreference *read_preference
     * }
     */
    public static final long read_preference$offset() {
        return read_preference$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct ReadPreference *read_preference
     * }
     */
    public static MemorySegment read_preference(MemorySegment struct) {
        return struct.get(read_preference$LAYOUT, read_preference$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct ReadPreference *read_preference
     * }
     */
    public static void read_preference(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(read_preference$LAYOUT, read_preference$OFFSET, fieldValue);
    }

    private static final AddressLayout write_concern$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("write_concern"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct WriteConcern *write_concern
     * }
     */
    public static final AddressLayout write_concern$layout() {
        return write_concern$LAYOUT;
    }

    private static final long write_concern$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct WriteConcern *write_concern
     * }
     */
    public static final long write_concern$offset() {
        return write_concern$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct WriteConcern *write_concern
     * }
     */
    public static MemorySegment write_concern(MemorySegment struct) {
        return struct.get(write_concern$LAYOUT, write_concern$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct WriteConcern *write_concern
     * }
     */
    public static void write_concern(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(write_concern$LAYOUT, write_concern$OFFSET, fieldValue);
    }

    private static final AddressLayout read_concern$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("read_concern"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct ReadConcern *read_concern
     * }
     */
    public static final AddressLayout read_concern$layout() {
        return read_concern$LAYOUT;
    }

    private static final long read_concern$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct ReadConcern *read_concern
     * }
     */
    public static final long read_concern$offset() {
        return read_concern$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct ReadConcern *read_concern
     * }
     */
    public static MemorySegment read_concern(MemorySegment struct) {
        return struct.get(read_concern$LAYOUT, read_concern$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct ReadConcern *read_concern
     * }
     */
    public static void read_concern(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(read_concern$LAYOUT, read_concern$OFFSET, fieldValue);
    }

    private static final OfLong timeout_ms$LAYOUT = (OfLong)$LAYOUT.select(groupElement("timeout_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t timeout_ms
     * }
     */
    public static final OfLong timeout_ms$layout() {
        return timeout_ms$LAYOUT;
    }

    private static final long timeout_ms$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t timeout_ms
     * }
     */
    public static final long timeout_ms$offset() {
        return timeout_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t timeout_ms
     * }
     */
    public static long timeout_ms(MemorySegment struct) {
        return struct.get(timeout_ms$LAYOUT, timeout_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t timeout_ms
     * }
     */
    public static void timeout_ms(MemorySegment struct, long fieldValue) {
        struct.set(timeout_ms$LAYOUT, timeout_ms$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

