// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct Bson {
 *     const uint8_t *data;
 *     size_t len;
 * } OwnedBson
 * }
 */
public class OwnedBson extends Bson {

    OwnedBson() {
        // Should not be called directly
    }
}

