// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ReadPreference {
 *     uint8_t _private[0];
 * }
 * }
 */
public class ReadPreference {

    ReadPreference() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(0, MongoDbFfi.C_CHAR).withName("_private")
    ).withName("ReadPreference");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout _private$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("_private"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t _private[0]
     * }
     */
    public static final SequenceLayout _private$layout() {
        return _private$LAYOUT;
    }

    private static final long _private$OFFSET = $LAYOUT.byteOffset(groupElement("_private"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t _private[0]
     * }
     */
    public static final long _private$offset() {
        return _private$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t _private[0]
     * }
     */
    public static MemorySegment _private(MemorySegment struct) {
        return struct.asSlice(_private$OFFSET, _private$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t _private[0]
     * }
     */
    public static void _private(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, _private$OFFSET, _private$LAYOUT.byteSize());
    }

    private static long[] _private$DIMS = { 0 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t _private[0]
     * }
     */
    public static long[] _private$dimensions() {
        return _private$DIMS;
    }
    private static final VarHandle _private$ELEM_HANDLE = _private$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t _private[0]
     * }
     */
    public static byte _private(MemorySegment struct, long index0) {
        return (byte)_private$ELEM_HANDLE.get(struct, _private$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t _private[0]
     * }
     */
    public static void _private(MemorySegment struct, long index0, byte fieldValue) {
        _private$ELEM_HANDLE.set(struct, _private$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

