// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ReadPreferenceOptions {
 *     uint8_t mode;
 *     const struct Bson *tags;
 *     int64_t max_staleness_seconds;
 *     const struct Bson *hedge;
 * }
 * }
 */
public class ReadPreferenceOptions {

    ReadPreferenceOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_CHAR.withName("mode"),
        MemoryLayout.paddingLayout(7),
        MongoDbFfi.C_POINTER.withName("tags"),
        MongoDbFfi.C_LONG_LONG.withName("max_staleness_seconds"),
        MongoDbFfi.C_POINTER.withName("hedge")
    ).withName("ReadPreferenceOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte mode$LAYOUT = (OfByte)$LAYOUT.select(groupElement("mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t mode
     * }
     */
    public static final OfByte mode$layout() {
        return mode$LAYOUT;
    }

    private static final long mode$OFFSET = $LAYOUT.byteOffset(groupElement("mode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t mode
     * }
     */
    public static final long mode$offset() {
        return mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t mode
     * }
     */
    public static byte mode(MemorySegment struct) {
        return struct.get(mode$LAYOUT, mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t mode
     * }
     */
    public static void mode(MemorySegment struct, byte fieldValue) {
        struct.set(mode$LAYOUT, mode$OFFSET, fieldValue);
    }

    private static final AddressLayout tags$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("tags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *tags
     * }
     */
    public static final AddressLayout tags$layout() {
        return tags$LAYOUT;
    }

    private static final long tags$OFFSET = $LAYOUT.byteOffset(groupElement("tags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *tags
     * }
     */
    public static final long tags$offset() {
        return tags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *tags
     * }
     */
    public static MemorySegment tags(MemorySegment struct) {
        return struct.get(tags$LAYOUT, tags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *tags
     * }
     */
    public static void tags(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(tags$LAYOUT, tags$OFFSET, fieldValue);
    }

    private static final OfLong max_staleness_seconds$LAYOUT = (OfLong)$LAYOUT.select(groupElement("max_staleness_seconds"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t max_staleness_seconds
     * }
     */
    public static final OfLong max_staleness_seconds$layout() {
        return max_staleness_seconds$LAYOUT;
    }

    private static final long max_staleness_seconds$OFFSET = $LAYOUT.byteOffset(groupElement("max_staleness_seconds"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t max_staleness_seconds
     * }
     */
    public static final long max_staleness_seconds$offset() {
        return max_staleness_seconds$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t max_staleness_seconds
     * }
     */
    public static long max_staleness_seconds(MemorySegment struct) {
        return struct.get(max_staleness_seconds$LAYOUT, max_staleness_seconds$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t max_staleness_seconds
     * }
     */
    public static void max_staleness_seconds(MemorySegment struct, long fieldValue) {
        struct.set(max_staleness_seconds$LAYOUT, max_staleness_seconds$OFFSET, fieldValue);
    }

    private static final AddressLayout hedge$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("hedge"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *hedge
     * }
     */
    public static final AddressLayout hedge$layout() {
        return hedge$LAYOUT;
    }

    private static final long hedge$OFFSET = $LAYOUT.byteOffset(groupElement("hedge"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *hedge
     * }
     */
    public static final long hedge$offset() {
        return hedge$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *hedge
     * }
     */
    public static MemorySegment hedge(MemorySegment struct) {
        return struct.get(hedge$LAYOUT, hedge$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *hedge
     * }
     */
    public static void hedge(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hedge$LAYOUT, hedge$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

