// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ReplaceOptions {
 *     int8_t upsert;
 *     int8_t bypass_document_validation;
 *     const struct BsonValue *hint;
 *     const struct Bson *collation;
 *     const struct BsonValue *comment;
 * }
 * }
 */
public class ReplaceOptions {

    ReplaceOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_CHAR.withName("upsert"),
        MongoDbFfi.C_CHAR.withName("bypass_document_validation"),
        MemoryLayout.paddingLayout(6),
        MongoDbFfi.C_POINTER.withName("hint"),
        MongoDbFfi.C_POINTER.withName("collation"),
        MongoDbFfi.C_POINTER.withName("comment")
    ).withName("ReplaceOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte upsert$LAYOUT = (OfByte)$LAYOUT.select(groupElement("upsert"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t upsert
     * }
     */
    public static final OfByte upsert$layout() {
        return upsert$LAYOUT;
    }

    private static final long upsert$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t upsert
     * }
     */
    public static final long upsert$offset() {
        return upsert$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t upsert
     * }
     */
    public static byte upsert(MemorySegment struct) {
        return struct.get(upsert$LAYOUT, upsert$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t upsert
     * }
     */
    public static void upsert(MemorySegment struct, byte fieldValue) {
        struct.set(upsert$LAYOUT, upsert$OFFSET, fieldValue);
    }

    private static final OfByte bypass_document_validation$LAYOUT = (OfByte)$LAYOUT.select(groupElement("bypass_document_validation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static final OfByte bypass_document_validation$layout() {
        return bypass_document_validation$LAYOUT;
    }

    private static final long bypass_document_validation$OFFSET = 1;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static final long bypass_document_validation$offset() {
        return bypass_document_validation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static byte bypass_document_validation(MemorySegment struct) {
        return struct.get(bypass_document_validation$LAYOUT, bypass_document_validation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t bypass_document_validation
     * }
     */
    public static void bypass_document_validation(MemorySegment struct, byte fieldValue) {
        struct.set(bypass_document_validation$LAYOUT, bypass_document_validation$OFFSET, fieldValue);
    }

    private static final AddressLayout hint$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("hint"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BsonValue *hint
     * }
     */
    public static final AddressLayout hint$layout() {
        return hint$LAYOUT;
    }

    private static final long hint$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BsonValue *hint
     * }
     */
    public static final long hint$offset() {
        return hint$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BsonValue *hint
     * }
     */
    public static MemorySegment hint(MemorySegment struct) {
        return struct.get(hint$LAYOUT, hint$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BsonValue *hint
     * }
     */
    public static void hint(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(hint$LAYOUT, hint$OFFSET, fieldValue);
    }

    private static final AddressLayout collation$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("collation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final AddressLayout collation$layout() {
        return collation$LAYOUT;
    }

    private static final long collation$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static final long collation$offset() {
        return collation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static MemorySegment collation(MemorySegment struct) {
        return struct.get(collation$LAYOUT, collation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct Bson *collation
     * }
     */
    public static void collation(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(collation$LAYOUT, collation$OFFSET, fieldValue);
    }

    private static final AddressLayout comment$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("comment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final AddressLayout comment$layout() {
        return comment$LAYOUT;
    }

    private static final long comment$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static final long comment$offset() {
        return comment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static MemorySegment comment(MemorySegment struct) {
        return struct.get(comment$LAYOUT, comment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BsonValue *comment
     * }
     */
    public static void comment(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(comment$LAYOUT, comment$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

