// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ServerError {
 *     int32_t code;
 *     const char *code_name;
 *     const char *message;
 *     const char *const *labels;
 *     uintptr_t labels_len;
 *     struct Bson server_response;
 * }
 * }
 */
public class ServerError {

    ServerError() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_INT.withName("code"),
        MemoryLayout.paddingLayout(4),
        MongoDbFfi.C_POINTER.withName("code_name"),
        MongoDbFfi.C_POINTER.withName("message"),
        MongoDbFfi.C_POINTER.withName("labels"),
        MongoDbFfi.C_LONG.withName("labels_len"),
        Bson.layout().withName("server_response")
    ).withName("ServerError");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt code$LAYOUT = (OfInt)$LAYOUT.select(groupElement("code"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t code
     * }
     */
    public static final OfInt code$layout() {
        return code$LAYOUT;
    }

    private static final long code$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t code
     * }
     */
    public static final long code$offset() {
        return code$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t code
     * }
     */
    public static int code(MemorySegment struct) {
        return struct.get(code$LAYOUT, code$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t code
     * }
     */
    public static void code(MemorySegment struct, int fieldValue) {
        struct.set(code$LAYOUT, code$OFFSET, fieldValue);
    }

    private static final AddressLayout code_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("code_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *code_name
     * }
     */
    public static final AddressLayout code_name$layout() {
        return code_name$LAYOUT;
    }

    private static final long code_name$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *code_name
     * }
     */
    public static final long code_name$offset() {
        return code_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *code_name
     * }
     */
    public static MemorySegment code_name(MemorySegment struct) {
        return struct.get(code_name$LAYOUT, code_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *code_name
     * }
     */
    public static void code_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(code_name$LAYOUT, code_name$OFFSET, fieldValue);
    }

    private static final AddressLayout message$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("message"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static final AddressLayout message$layout() {
        return message$LAYOUT;
    }

    private static final long message$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static final long message$offset() {
        return message$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static MemorySegment message(MemorySegment struct) {
        return struct.get(message$LAYOUT, message$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static void message(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(message$LAYOUT, message$OFFSET, fieldValue);
    }

    private static final AddressLayout labels$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("labels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *const *labels
     * }
     */
    public static final AddressLayout labels$layout() {
        return labels$LAYOUT;
    }

    private static final long labels$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *const *labels
     * }
     */
    public static final long labels$offset() {
        return labels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *const *labels
     * }
     */
    public static MemorySegment labels(MemorySegment struct) {
        return struct.get(labels$LAYOUT, labels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *const *labels
     * }
     */
    public static void labels(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(labels$LAYOUT, labels$OFFSET, fieldValue);
    }

    private static final OfLong labels_len$LAYOUT = (OfLong)$LAYOUT.select(groupElement("labels_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uintptr_t labels_len
     * }
     */
    public static final OfLong labels_len$layout() {
        return labels_len$LAYOUT;
    }

    private static final long labels_len$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uintptr_t labels_len
     * }
     */
    public static final long labels_len$offset() {
        return labels_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uintptr_t labels_len
     * }
     */
    public static long labels_len(MemorySegment struct) {
        return struct.get(labels_len$LAYOUT, labels_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uintptr_t labels_len
     * }
     */
    public static void labels_len(MemorySegment struct, long fieldValue) {
        struct.set(labels_len$LAYOUT, labels_len$OFFSET, fieldValue);
    }

    private static final GroupLayout server_response$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("server_response"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct Bson server_response
     * }
     */
    public static final GroupLayout server_response$layout() {
        return server_response$LAYOUT;
    }

    private static final long server_response$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct Bson server_response
     * }
     */
    public static final long server_response$offset() {
        return server_response$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct Bson server_response
     * }
     */
    public static MemorySegment server_response(MemorySegment struct) {
        return struct.asSlice(server_response$OFFSET, server_response$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct Bson server_response
     * }
     */
    public static void server_response(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, server_response$OFFSET, server_response$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

