// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SessionOptionsFFI {
 *     int8_t causal_consistency;
 *     int8_t snapshot;
 *     const struct TransactionOptionsFFI *default_transaction_options;
 * }
 * }
 */
public class SessionOptionsFFI {

    SessionOptionsFFI() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_CHAR.withName("causal_consistency"),
        MongoDbFfi.C_CHAR.withName("snapshot"),
        MemoryLayout.paddingLayout(6),
        MongoDbFfi.C_POINTER.withName("default_transaction_options")
    ).withName("SessionOptionsFFI");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte causal_consistency$LAYOUT = (OfByte)$LAYOUT.select(groupElement("causal_consistency"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t causal_consistency
     * }
     */
    public static final OfByte causal_consistency$layout() {
        return causal_consistency$LAYOUT;
    }

    private static final long causal_consistency$OFFSET = $LAYOUT.byteOffset(groupElement("causal_consistency"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t causal_consistency
     * }
     */
    public static final long causal_consistency$offset() {
        return causal_consistency$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t causal_consistency
     * }
     */
    public static byte causal_consistency(MemorySegment struct) {
        return struct.get(causal_consistency$LAYOUT, causal_consistency$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t causal_consistency
     * }
     */
    public static void causal_consistency(MemorySegment struct, byte fieldValue) {
        struct.set(causal_consistency$LAYOUT, causal_consistency$OFFSET, fieldValue);
    }

    private static final OfByte snapshot$LAYOUT = (OfByte)$LAYOUT.select(groupElement("snapshot"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t snapshot
     * }
     */
    public static final OfByte snapshot$layout() {
        return snapshot$LAYOUT;
    }

    private static final long snapshot$OFFSET = $LAYOUT.byteOffset(groupElement("snapshot"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t snapshot
     * }
     */
    public static final long snapshot$offset() {
        return snapshot$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t snapshot
     * }
     */
    public static byte snapshot(MemorySegment struct) {
        return struct.get(snapshot$LAYOUT, snapshot$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t snapshot
     * }
     */
    public static void snapshot(MemorySegment struct, byte fieldValue) {
        struct.set(snapshot$LAYOUT, snapshot$OFFSET, fieldValue);
    }

    private static final AddressLayout default_transaction_options$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("default_transaction_options"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct TransactionOptionsFFI *default_transaction_options
     * }
     */
    public static final AddressLayout default_transaction_options$layout() {
        return default_transaction_options$LAYOUT;
    }

    private static final long default_transaction_options$OFFSET = $LAYOUT.byteOffset(groupElement("default_transaction_options"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct TransactionOptionsFFI *default_transaction_options
     * }
     */
    public static final long default_transaction_options$offset() {
        return default_transaction_options$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct TransactionOptionsFFI *default_transaction_options
     * }
     */
    public static MemorySegment default_transaction_options(MemorySegment struct) {
        return struct.get(default_transaction_options$LAYOUT, default_transaction_options$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct TransactionOptionsFFI *default_transaction_options
     * }
     */
    public static void default_transaction_options(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(default_transaction_options$LAYOUT, default_transaction_options$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

