// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TlsSettings {
 *     bool enabled;
 *     bool allow_invalid_certificates;
 *     bool allow_invalid_hostnames;
 *     const char *ca_file;
 *     const char *cert_file;
 *     const char *cert_key_file;
 * }
 * }
 */
public class TlsSettings {

    TlsSettings() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_BOOL.withName("enabled"),
        MongoDbFfi.C_BOOL.withName("allow_invalid_certificates"),
        MongoDbFfi.C_BOOL.withName("allow_invalid_hostnames"),
        MemoryLayout.paddingLayout(5),
        MongoDbFfi.C_POINTER.withName("ca_file"),
        MongoDbFfi.C_POINTER.withName("cert_file"),
        MongoDbFfi.C_POINTER.withName("cert_key_file")
    ).withName("TlsSettings");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfBoolean enabled$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("enabled"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool enabled
     * }
     */
    public static final OfBoolean enabled$layout() {
        return enabled$LAYOUT;
    }

    private static final long enabled$OFFSET = $LAYOUT.byteOffset(groupElement("enabled"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool enabled
     * }
     */
    public static final long enabled$offset() {
        return enabled$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool enabled
     * }
     */
    public static boolean enabled(MemorySegment struct) {
        return struct.get(enabled$LAYOUT, enabled$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool enabled
     * }
     */
    public static void enabled(MemorySegment struct, boolean fieldValue) {
        struct.set(enabled$LAYOUT, enabled$OFFSET, fieldValue);
    }

    private static final OfBoolean allow_invalid_certificates$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("allow_invalid_certificates"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool allow_invalid_certificates
     * }
     */
    public static final OfBoolean allow_invalid_certificates$layout() {
        return allow_invalid_certificates$LAYOUT;
    }

    private static final long allow_invalid_certificates$OFFSET = $LAYOUT.byteOffset(groupElement("allow_invalid_certificates"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool allow_invalid_certificates
     * }
     */
    public static final long allow_invalid_certificates$offset() {
        return allow_invalid_certificates$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool allow_invalid_certificates
     * }
     */
    public static boolean allow_invalid_certificates(MemorySegment struct) {
        return struct.get(allow_invalid_certificates$LAYOUT, allow_invalid_certificates$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool allow_invalid_certificates
     * }
     */
    public static void allow_invalid_certificates(MemorySegment struct, boolean fieldValue) {
        struct.set(allow_invalid_certificates$LAYOUT, allow_invalid_certificates$OFFSET, fieldValue);
    }

    private static final OfBoolean allow_invalid_hostnames$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("allow_invalid_hostnames"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool allow_invalid_hostnames
     * }
     */
    public static final OfBoolean allow_invalid_hostnames$layout() {
        return allow_invalid_hostnames$LAYOUT;
    }

    private static final long allow_invalid_hostnames$OFFSET = $LAYOUT.byteOffset(groupElement("allow_invalid_hostnames"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool allow_invalid_hostnames
     * }
     */
    public static final long allow_invalid_hostnames$offset() {
        return allow_invalid_hostnames$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool allow_invalid_hostnames
     * }
     */
    public static boolean allow_invalid_hostnames(MemorySegment struct) {
        return struct.get(allow_invalid_hostnames$LAYOUT, allow_invalid_hostnames$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool allow_invalid_hostnames
     * }
     */
    public static void allow_invalid_hostnames(MemorySegment struct, boolean fieldValue) {
        struct.set(allow_invalid_hostnames$LAYOUT, allow_invalid_hostnames$OFFSET, fieldValue);
    }

    private static final AddressLayout ca_file$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ca_file"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *ca_file
     * }
     */
    public static final AddressLayout ca_file$layout() {
        return ca_file$LAYOUT;
    }

    private static final long ca_file$OFFSET = $LAYOUT.byteOffset(groupElement("ca_file"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *ca_file
     * }
     */
    public static final long ca_file$offset() {
        return ca_file$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *ca_file
     * }
     */
    public static MemorySegment ca_file(MemorySegment struct) {
        return struct.get(ca_file$LAYOUT, ca_file$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *ca_file
     * }
     */
    public static void ca_file(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ca_file$LAYOUT, ca_file$OFFSET, fieldValue);
    }

    private static final AddressLayout cert_file$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cert_file"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *cert_file
     * }
     */
    public static final AddressLayout cert_file$layout() {
        return cert_file$LAYOUT;
    }

    private static final long cert_file$OFFSET = $LAYOUT.byteOffset(groupElement("cert_file"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *cert_file
     * }
     */
    public static final long cert_file$offset() {
        return cert_file$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *cert_file
     * }
     */
    public static MemorySegment cert_file(MemorySegment struct) {
        return struct.get(cert_file$LAYOUT, cert_file$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *cert_file
     * }
     */
    public static void cert_file(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cert_file$LAYOUT, cert_file$OFFSET, fieldValue);
    }

    private static final AddressLayout cert_key_file$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cert_key_file"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *cert_key_file
     * }
     */
    public static final AddressLayout cert_key_file$layout() {
        return cert_key_file$LAYOUT;
    }

    private static final long cert_key_file$OFFSET = $LAYOUT.byteOffset(groupElement("cert_key_file"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *cert_key_file
     * }
     */
    public static final long cert_key_file$offset() {
        return cert_key_file$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *cert_key_file
     * }
     */
    public static MemorySegment cert_key_file(MemorySegment struct) {
        return struct.get(cert_key_file$LAYOUT, cert_key_file$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *cert_key_file
     * }
     */
    public static void cert_key_file(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cert_key_file$LAYOUT, cert_key_file$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

