// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TransactionOptions {
 *     const char *read_concern_level;
 *     int32_t write_concern_w;
 *     const char *write_concern_w_tag;
 *     int8_t write_concern_j;
 *     int64_t write_concern_w_timeout_ms;
 *     uint8_t read_preference_mode;
 *     int64_t max_commit_time_ms;
 * }
 * }
 */
public class TransactionOptions {

    TransactionOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_POINTER.withName("read_concern_level"),
        MongoDbFfi.C_INT.withName("write_concern_w"),
        MemoryLayout.paddingLayout(4),
        MongoDbFfi.C_POINTER.withName("write_concern_w_tag"),
        MongoDbFfi.C_CHAR.withName("write_concern_j"),
        MemoryLayout.paddingLayout(7),
        MongoDbFfi.C_LONG_LONG.withName("write_concern_w_timeout_ms"),
        MongoDbFfi.C_CHAR.withName("read_preference_mode"),
        MemoryLayout.paddingLayout(7),
        MongoDbFfi.C_LONG_LONG.withName("max_commit_time_ms")
    ).withName("TransactionOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout read_concern_level$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("read_concern_level"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *read_concern_level
     * }
     */
    public static final AddressLayout read_concern_level$layout() {
        return read_concern_level$LAYOUT;
    }

    private static final long read_concern_level$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *read_concern_level
     * }
     */
    public static final long read_concern_level$offset() {
        return read_concern_level$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *read_concern_level
     * }
     */
    public static MemorySegment read_concern_level(MemorySegment struct) {
        return struct.get(read_concern_level$LAYOUT, read_concern_level$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *read_concern_level
     * }
     */
    public static void read_concern_level(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(read_concern_level$LAYOUT, read_concern_level$OFFSET, fieldValue);
    }

    private static final OfInt write_concern_w$LAYOUT = (OfInt)$LAYOUT.select(groupElement("write_concern_w"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t write_concern_w
     * }
     */
    public static final OfInt write_concern_w$layout() {
        return write_concern_w$LAYOUT;
    }

    private static final long write_concern_w$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t write_concern_w
     * }
     */
    public static final long write_concern_w$offset() {
        return write_concern_w$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t write_concern_w
     * }
     */
    public static int write_concern_w(MemorySegment struct) {
        return struct.get(write_concern_w$LAYOUT, write_concern_w$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t write_concern_w
     * }
     */
    public static void write_concern_w(MemorySegment struct, int fieldValue) {
        struct.set(write_concern_w$LAYOUT, write_concern_w$OFFSET, fieldValue);
    }

    private static final AddressLayout write_concern_w_tag$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("write_concern_w_tag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *write_concern_w_tag
     * }
     */
    public static final AddressLayout write_concern_w_tag$layout() {
        return write_concern_w_tag$LAYOUT;
    }

    private static final long write_concern_w_tag$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *write_concern_w_tag
     * }
     */
    public static final long write_concern_w_tag$offset() {
        return write_concern_w_tag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *write_concern_w_tag
     * }
     */
    public static MemorySegment write_concern_w_tag(MemorySegment struct) {
        return struct.get(write_concern_w_tag$LAYOUT, write_concern_w_tag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *write_concern_w_tag
     * }
     */
    public static void write_concern_w_tag(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(write_concern_w_tag$LAYOUT, write_concern_w_tag$OFFSET, fieldValue);
    }

    private static final OfByte write_concern_j$LAYOUT = (OfByte)$LAYOUT.select(groupElement("write_concern_j"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t write_concern_j
     * }
     */
    public static final OfByte write_concern_j$layout() {
        return write_concern_j$LAYOUT;
    }

    private static final long write_concern_j$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t write_concern_j
     * }
     */
    public static final long write_concern_j$offset() {
        return write_concern_j$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t write_concern_j
     * }
     */
    public static byte write_concern_j(MemorySegment struct) {
        return struct.get(write_concern_j$LAYOUT, write_concern_j$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t write_concern_j
     * }
     */
    public static void write_concern_j(MemorySegment struct, byte fieldValue) {
        struct.set(write_concern_j$LAYOUT, write_concern_j$OFFSET, fieldValue);
    }

    private static final OfLong write_concern_w_timeout_ms$LAYOUT = (OfLong)$LAYOUT.select(groupElement("write_concern_w_timeout_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t write_concern_w_timeout_ms
     * }
     */
    public static final OfLong write_concern_w_timeout_ms$layout() {
        return write_concern_w_timeout_ms$LAYOUT;
    }

    private static final long write_concern_w_timeout_ms$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t write_concern_w_timeout_ms
     * }
     */
    public static final long write_concern_w_timeout_ms$offset() {
        return write_concern_w_timeout_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t write_concern_w_timeout_ms
     * }
     */
    public static long write_concern_w_timeout_ms(MemorySegment struct) {
        return struct.get(write_concern_w_timeout_ms$LAYOUT, write_concern_w_timeout_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t write_concern_w_timeout_ms
     * }
     */
    public static void write_concern_w_timeout_ms(MemorySegment struct, long fieldValue) {
        struct.set(write_concern_w_timeout_ms$LAYOUT, write_concern_w_timeout_ms$OFFSET, fieldValue);
    }

    private static final OfByte read_preference_mode$LAYOUT = (OfByte)$LAYOUT.select(groupElement("read_preference_mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t read_preference_mode
     * }
     */
    public static final OfByte read_preference_mode$layout() {
        return read_preference_mode$LAYOUT;
    }

    private static final long read_preference_mode$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t read_preference_mode
     * }
     */
    public static final long read_preference_mode$offset() {
        return read_preference_mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t read_preference_mode
     * }
     */
    public static byte read_preference_mode(MemorySegment struct) {
        return struct.get(read_preference_mode$LAYOUT, read_preference_mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t read_preference_mode
     * }
     */
    public static void read_preference_mode(MemorySegment struct, byte fieldValue) {
        struct.set(read_preference_mode$LAYOUT, read_preference_mode$OFFSET, fieldValue);
    }

    private static final OfLong max_commit_time_ms$LAYOUT = (OfLong)$LAYOUT.select(groupElement("max_commit_time_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t max_commit_time_ms
     * }
     */
    public static final OfLong max_commit_time_ms$layout() {
        return max_commit_time_ms$LAYOUT;
    }

    private static final long max_commit_time_ms$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t max_commit_time_ms
     * }
     */
    public static final long max_commit_time_ms$offset() {
        return max_commit_time_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t max_commit_time_ms
     * }
     */
    public static long max_commit_time_ms(MemorySegment struct) {
        return struct.get(max_commit_time_ms$LAYOUT, max_commit_time_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t max_commit_time_ms
     * }
     */
    public static void max_commit_time_ms(MemorySegment struct, long fieldValue) {
        struct.set(max_commit_time_ms$LAYOUT, max_commit_time_ms$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

