// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TransactionError {
 *     const char *message;
 *     const char *const *labels;
 *     uintptr_t labels_len;
 * }
 * }
 */
public class TransactionError {

    TransactionError() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_POINTER.withName("message"),
        MongoDbFfi.C_POINTER.withName("labels"),
        MongoDbFfi.C_LONG.withName("labels_len")
    ).withName("TransactionError");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout message$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("message"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static final AddressLayout message$layout() {
        return message$LAYOUT;
    }

    private static final long message$OFFSET = $LAYOUT.byteOffset(groupElement("message"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static final long message$offset() {
        return message$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static MemorySegment message(MemorySegment struct) {
        return struct.get(message$LAYOUT, message$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static void message(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(message$LAYOUT, message$OFFSET, fieldValue);
    }

    private static final AddressLayout labels$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("labels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *const *labels
     * }
     */
    public static final AddressLayout labels$layout() {
        return labels$LAYOUT;
    }

    private static final long labels$OFFSET = $LAYOUT.byteOffset(groupElement("labels"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *const *labels
     * }
     */
    public static final long labels$offset() {
        return labels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *const *labels
     * }
     */
    public static MemorySegment labels(MemorySegment struct) {
        return struct.get(labels$LAYOUT, labels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *const *labels
     * }
     */
    public static void labels(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(labels$LAYOUT, labels$OFFSET, fieldValue);
    }

    private static final OfLong labels_len$LAYOUT = (OfLong)$LAYOUT.select(groupElement("labels_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uintptr_t labels_len
     * }
     */
    public static final OfLong labels_len$layout() {
        return labels_len$LAYOUT;
    }

    private static final long labels_len$OFFSET = $LAYOUT.byteOffset(groupElement("labels_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uintptr_t labels_len
     * }
     */
    public static final long labels_len$offset() {
        return labels_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uintptr_t labels_len
     * }
     */
    public static long labels_len(MemorySegment struct) {
        return struct.get(labels_len$LAYOUT, labels_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uintptr_t labels_len
     * }
     */
    public static void labels_len(MemorySegment struct, long fieldValue) {
        struct.set(labels_len$LAYOUT, labels_len$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

