// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct UpdateResult {
 *     uint64_t matched_count;
 *     uint64_t modified_count;
 *     const struct BsonValue *upserted_id;
 * }
 * }
 */
public class UpdateResult {

    UpdateResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_LONG_LONG.withName("matched_count"),
        MongoDbFfi.C_LONG_LONG.withName("modified_count"),
        MongoDbFfi.C_POINTER.withName("upserted_id")
    ).withName("UpdateResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong matched_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("matched_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t matched_count
     * }
     */
    public static final OfLong matched_count$layout() {
        return matched_count$LAYOUT;
    }

    private static final long matched_count$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t matched_count
     * }
     */
    public static final long matched_count$offset() {
        return matched_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t matched_count
     * }
     */
    public static long matched_count(MemorySegment struct) {
        return struct.get(matched_count$LAYOUT, matched_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t matched_count
     * }
     */
    public static void matched_count(MemorySegment struct, long fieldValue) {
        struct.set(matched_count$LAYOUT, matched_count$OFFSET, fieldValue);
    }

    private static final OfLong modified_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("modified_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t modified_count
     * }
     */
    public static final OfLong modified_count$layout() {
        return modified_count$LAYOUT;
    }

    private static final long modified_count$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t modified_count
     * }
     */
    public static final long modified_count$offset() {
        return modified_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t modified_count
     * }
     */
    public static long modified_count(MemorySegment struct) {
        return struct.get(modified_count$LAYOUT, modified_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t modified_count
     * }
     */
    public static void modified_count(MemorySegment struct, long fieldValue) {
        struct.set(modified_count$LAYOUT, modified_count$OFFSET, fieldValue);
    }

    private static final AddressLayout upserted_id$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("upserted_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct BsonValue *upserted_id
     * }
     */
    public static final AddressLayout upserted_id$layout() {
        return upserted_id$LAYOUT;
    }

    private static final long upserted_id$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct BsonValue *upserted_id
     * }
     */
    public static final long upserted_id$offset() {
        return upserted_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct BsonValue *upserted_id
     * }
     */
    public static MemorySegment upserted_id(MemorySegment struct) {
        return struct.get(upserted_id$LAYOUT, upserted_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct BsonValue *upserted_id
     * }
     */
    public static void upserted_id(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(upserted_id$LAYOUT, upserted_id$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

