// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WriteConcernOptions {
 *     int32_t w;
 *     const char *w_tag;
 *     int8_t journal;
 *     int64_t w_timeout_ms;
 * }
 * }
 */
public class WriteConcernOptions {

    WriteConcernOptions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_INT.withName("w"),
        MemoryLayout.paddingLayout(4),
        MongoDbFfi.C_POINTER.withName("w_tag"),
        MongoDbFfi.C_CHAR.withName("journal"),
        MemoryLayout.paddingLayout(7),
        MongoDbFfi.C_LONG_LONG.withName("w_timeout_ms")
    ).withName("WriteConcernOptions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt w$LAYOUT = (OfInt)$LAYOUT.select(groupElement("w"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t w
     * }
     */
    public static final OfInt w$layout() {
        return w$LAYOUT;
    }

    private static final long w$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t w
     * }
     */
    public static final long w$offset() {
        return w$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t w
     * }
     */
    public static int w(MemorySegment struct) {
        return struct.get(w$LAYOUT, w$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t w
     * }
     */
    public static void w(MemorySegment struct, int fieldValue) {
        struct.set(w$LAYOUT, w$OFFSET, fieldValue);
    }

    private static final AddressLayout w_tag$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("w_tag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *w_tag
     * }
     */
    public static final AddressLayout w_tag$layout() {
        return w_tag$LAYOUT;
    }

    private static final long w_tag$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *w_tag
     * }
     */
    public static final long w_tag$offset() {
        return w_tag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *w_tag
     * }
     */
    public static MemorySegment w_tag(MemorySegment struct) {
        return struct.get(w_tag$LAYOUT, w_tag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *w_tag
     * }
     */
    public static void w_tag(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(w_tag$LAYOUT, w_tag$OFFSET, fieldValue);
    }

    private static final OfByte journal$LAYOUT = (OfByte)$LAYOUT.select(groupElement("journal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t journal
     * }
     */
    public static final OfByte journal$layout() {
        return journal$LAYOUT;
    }

    private static final long journal$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t journal
     * }
     */
    public static final long journal$offset() {
        return journal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t journal
     * }
     */
    public static byte journal(MemorySegment struct) {
        return struct.get(journal$LAYOUT, journal$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t journal
     * }
     */
    public static void journal(MemorySegment struct, byte fieldValue) {
        struct.set(journal$LAYOUT, journal$OFFSET, fieldValue);
    }

    private static final OfLong w_timeout_ms$LAYOUT = (OfLong)$LAYOUT.select(groupElement("w_timeout_ms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t w_timeout_ms
     * }
     */
    public static final OfLong w_timeout_ms$layout() {
        return w_timeout_ms$LAYOUT;
    }

    private static final long w_timeout_ms$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t w_timeout_ms
     * }
     */
    public static final long w_timeout_ms$offset() {
        return w_timeout_ms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t w_timeout_ms
     * }
     */
    public static long w_timeout_ms(MemorySegment struct) {
        return struct.get(w_timeout_ms$LAYOUT, w_timeout_ms$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t w_timeout_ms
     * }
     */
    public static void w_timeout_ms(MemorySegment struct, long fieldValue) {
        struct.set(w_timeout_ms$LAYOUT, w_timeout_ms$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

