// Generated by jextract

package com.mongodb.internal.rust.crud.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct WriteError {
 *     uint32_t index;
 *     int32_t code;
 *     const char *code_name;
 *     const char *message;
 *     OwnedBson details;
 * }
 * }
 */
public class WriteError {

    WriteError() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MongoDbFfi.C_INT.withName("index"),
        MongoDbFfi.C_INT.withName("code"),
        MongoDbFfi.C_POINTER.withName("code_name"),
        MongoDbFfi.C_POINTER.withName("message"),
        Bson.layout().withName("details")
    ).withName("WriteError");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt index$LAYOUT = (OfInt)$LAYOUT.select(groupElement("index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t index
     * }
     */
    public static final OfInt index$layout() {
        return index$LAYOUT;
    }

    private static final long index$OFFSET = $LAYOUT.byteOffset(groupElement("index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t index
     * }
     */
    public static final long index$offset() {
        return index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t index
     * }
     */
    public static int index(MemorySegment struct) {
        return struct.get(index$LAYOUT, index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t index
     * }
     */
    public static void index(MemorySegment struct, int fieldValue) {
        struct.set(index$LAYOUT, index$OFFSET, fieldValue);
    }

    private static final OfInt code$LAYOUT = (OfInt)$LAYOUT.select(groupElement("code"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t code
     * }
     */
    public static final OfInt code$layout() {
        return code$LAYOUT;
    }

    private static final long code$OFFSET = $LAYOUT.byteOffset(groupElement("code"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t code
     * }
     */
    public static final long code$offset() {
        return code$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t code
     * }
     */
    public static int code(MemorySegment struct) {
        return struct.get(code$LAYOUT, code$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t code
     * }
     */
    public static void code(MemorySegment struct, int fieldValue) {
        struct.set(code$LAYOUT, code$OFFSET, fieldValue);
    }

    private static final AddressLayout code_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("code_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *code_name
     * }
     */
    public static final AddressLayout code_name$layout() {
        return code_name$LAYOUT;
    }

    private static final long code_name$OFFSET = $LAYOUT.byteOffset(groupElement("code_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *code_name
     * }
     */
    public static final long code_name$offset() {
        return code_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *code_name
     * }
     */
    public static MemorySegment code_name(MemorySegment struct) {
        return struct.get(code_name$LAYOUT, code_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *code_name
     * }
     */
    public static void code_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(code_name$LAYOUT, code_name$OFFSET, fieldValue);
    }

    private static final AddressLayout message$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("message"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static final AddressLayout message$layout() {
        return message$LAYOUT;
    }

    private static final long message$OFFSET = $LAYOUT.byteOffset(groupElement("message"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static final long message$offset() {
        return message$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static MemorySegment message(MemorySegment struct) {
        return struct.get(message$LAYOUT, message$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *message
     * }
     */
    public static void message(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(message$LAYOUT, message$OFFSET, fieldValue);
    }

    private static final GroupLayout details$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("details"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OwnedBson details
     * }
     */
    public static final GroupLayout details$layout() {
        return details$LAYOUT;
    }

    private static final long details$OFFSET = $LAYOUT.byteOffset(groupElement("details"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OwnedBson details
     * }
     */
    public static final long details$offset() {
        return details$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OwnedBson details
     * }
     */
    public static MemorySegment details(MemorySegment struct) {
        return struct.asSlice(details$OFFSET, details$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OwnedBson details
     * }
     */
    public static void details(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, details$OFFSET, details$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

