---
differenceTypes: []

packages:
- io.netty.*
- org.slf4j.*

classes:
  - org.bson.codecs.configuration.Optional$Some

members:
  org.bson.AbstractBsonReader:
  - doReadDecimal128()
  - doPeekBinarySize()
  org.bson.AbstractBsonWriter:
  - doWriteDecimal128(org.bson.types.Decimal128)
  org.bson.BsonNumber:
  - decimal128Value()
  org.bson.BsonReader:
  - readDecimal128()
  - readDecimal128(java.lang.String)
  - peekBinarySize()
  - getMark()
  - close()
  org.bson.io.BsonInput:
  - getMark(int)
  org.bson.BsonWriter:
  - writeDecimal128(org.bson.types.Decimal128)
  - writeDecimal128(java.lang.String,org.bson.types.Decimal128)
  - pipe(org.bson.BsonReader,java.util.List)
  org.bson.diagnostics.Loggers:
  - getLogger(java.lang.String)
